# Using pynsee melodi functions

## I. Install and uninstall a Python module from a GitHub repository

To install the pynsee module from a GitHub repository, run the following line in the terminal: pip install git+https://github.com/Mathieu-David/pynsee.git@MELODI.

If you want to uninstall it, run the following command in a terminal: pip uninstall pynsee

To list the installed Python modules, run the following command in a terminal: pip list

To execute a command in a terminal: press the "Enter" key.

## II. Load the pynsee module

In [1]:
# Load the entire pynsee module
import pynsee

C:\INSEE\LogicielsPortables\AppData\Roaming\Python\Python314\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## III. List of melodi functions

In [2]:
# Load the inspect module for object introspection
import inspect

# Extract and display all functions from the melodi submodule
fonctions_melodi = [
    nom for nom, obj in inspect.getmembers(pynsee.melodi, inspect.isfunction)
]

# Display the list of functions in the melodi submodule
print("Functions of the melodi submodule:")
for f in sorted(fonctions_melodi):
    print(f"- {f}")

Functions of the melodi submodule:
- get_all_data
- get_catalog
- get_data
- get_file
- get_local_data
- get_local_data_by_com
- get_metadata
- get_range
- get_range_geo

## IV. Help on pynsee melodi functions

In [3]:
# Help for all functions in the melodi submodule
help(pynsee.melodi)

Help on package pynsee.melodi in pynsee:

NAME
    pynsee.melodi

PACKAGE CONTENTS
    constants
    get_all_data
    get_catalog
    get_data
    get_file
    get_local_data
    get_local_data_by_com
    get_metadata
    get_range
    get_range_geo

FUNCTIONS
    get_all_data(
        ds_name: str,
        base_url_melodi: str = 'https://api.insee.fr/melodi',
        download_directory: str = None,
        stringsAsCategories: bool = False,
        remove_file: bool = True
    )
        Description
        ----------

        Get all data from a dataset.

        Parameters
        ----------

        ds_name : dataset name - use get_ds_list to find a dataset identifier

        base_url_melodi : API Melodi URL - default production URL : "https://api.insee.fr/melodi"

        download_directory : download directory - default system tempdir

        stringsAsCategories : if TRUE, strings variables in DataFrame are converted to categories - default FALSE

        remove_file : remove downloaded data file after loading data - default TRUE

        Returns
        -------

        A tuple consisting of one DataFrame holding the data and another holding the metadata.

        Examples
        --------

        tuple=pynsee.get_all_data("DS_TICM_PRATIQUES")

        #data
        data=tuple[0]
        data.info()
        data.head()

        #metadata
        metadata=tuple[1]
        metadata.info()
        metadata.head()

    get_catalog(
        lang: str = 'fr',
        base_url_melodi: str = 'https://api.insee.fr/melodi'
    ) -> pd.DataFrame
        Description
        ----------

        Get list of available datasets.

        Parameters
        ----------

        lang : str, {"fr", "en"}, default "fr"
            Language of metadata.

        base_url_melodi : str, default "https://api.insee.fr/melodi"
            Base URL of the Melodi API.

        Returns
        -------

        DataFrame with columns: identifier, title_content,
        subtitle_content, description_content, abstract_content,
        temporal_startPeriod, temporal_endPeriod, modified,
        numObservations, numSeries.

        Raises
        ------

        ValueError
            If ``lang`` is not 'fr' or 'en'.

        Examples
        --------
        Example 1: Get the catalog in French (default)

        catalogue_melodi = pynsee.get_catalog()
        catalogue_melodi.head()

        Example 2: Get the catalog in English

        catalogue_melodi = pynsee.get_catalog(lang="en")
        catalogue_melodi.head()

    get_data(url: str) -> pd.DataFrame
        Description
        ----------

        Get Melodi data by URL.
        URL parameter can be copied/pasted from explorer https://catalogue-donnees.insee.fr.

        Parameters
        ----------

        url : URL API data Melodi - Start by "https://api.insee.fr/melodi/data/..."

        Returns
        -------

        DataFrame with data.

        Examples
        --------

        data=pynsee.get_data("https://api.insee.fr/melodi/data/DS_POPULATIONS_REFERENCE?POPREF_MEASURE=PMUN&GEO=FRANCE-F")

        data.info()
        data.head()

    get_file(
        ds_name: str,
        download_file_name: str = None,
        file_name: str = None,
        download_directory: str = None,
        base_url_melodi: str = 'https://api.insee.fr/melodi'
    ) -> str
        Description
        ----------

        Get file attached to a dataset : extract (XLSX), or full CSV file, or full parquet file.

        Parameters
        ----------

        ds_name : dataset name

        file_name : file name, optional. Omit this parameter to get the Parquet file

        download_file_name : filename on disk after download, optional. Omit this parameter to get the Parquet file

        download_directory : download directory - default system tempdir

        base_url_melodi : API Melodi URL - default production URL : "https://api.insee.fr/melodi"

        Returns
        -------

        The path of the downloaded file.

        Examples
        --------

        Example 1 : download the XLSX associated with a dataset

        pynsee.get_file(ds_name = "DS_EC_DECES",
                 file_name = "T1_DECES_JOUR_NAT_FR",
                 download_file_name = "T1_DECES_JOUR_NAT_FR.xlsx")

        Example 2 : download the CSV in an archive that corresponds to the dataset

        pynsee.get_file(ds_name = "DS_EC_DECES",
                 file_name = "DS_EC_DECES_CSV_FR",
                 download_file_name = "DS_EC_DECES_CSV_FR.zip")

        Example 3 : download the parquet file that corresponds to the dataset

        pynsee.get_file(ds_name = "DS_RP_SERIE_HISTORIQUE")

    get_local_data(
        ds_name: str,
        geo: str,
        geo_object: str,
        query_filter: str = '',
        base_url_melodi: str = 'https://api.insee.fr/melodi'
    ) -> pd.DataFrame
        Description
        ----------

        Get data on one territory.

        Parameters
        ----------

        ds_name : dataset name - use get_ds_list to find a dataset identifier

        geo : code geo

        geo_object : geo level

        query_filter : additionnal filter on request - default : ""

        base_url_melodi : API Melodi URL - default production URL : "https://api.insee.fr/melodi"

        Returns
        -------

        DataFrame with data.

        Examples
        --------

        Example 1 :

        data=pynsee.get_local_data(

          ds_name = "DS_POPULATIONS_REFERENCE",

          geo = "69",

          geo_object = "DEP")

        data.info()
        data.head()

        Example 2 :

        data=pynsee.get_local_data(

          ds_name = "DS_POPULATIONS_REFERENCE",

          geo = "69",

          geo_object = "DEP",

          query_filter = "POPREF_MEASURE=PMUN")

        data.info()
        data.head()

    get_local_data_by_com(
        ds_name: str,
        geo: str,
        geo_object: str,
        query_filter: str = '',
        base_url_melodi: str = 'https://api.insee.fr/melodi'
    ) -> pd.DataFrame
        Description
        ----------

        Get data on every Commune of one territory.

        Parameters
        ----------

        ds_name : dataset name - use get_ds_list to find a dataset identifier

        geo : code geo

        geo_object : geo level

        query_filter : additionnal filter on request - default : ""

        base_url_melodi : API Melodi URL - default production URL : "https://api.insee.fr/melodi"

        Returns
        -------

        DataFrame with data.

        Examples
        --------

        Example 1 :

        data=pynsee.get_local_data_by_com(

          ds_name = "DS_POPULATIONS_REFERENCE",

          geo = "69",

          geo_object = "DEP")

        data.info()
        data.head()

        Example 2 :

        data=pynsee.get_local_data_by_com(

          ds_name = "DS_POPULATIONS_REFERENCE",

          geo = "69",

          geo_object = "DEP",

          query_filter = "POPREF_MEASURE=PMUN")

        data.info()
        data.head()

    get_metadata(ds_name: str, base_url_melodi: str = 'https://api.insee.fr/melodi')
        Description
        ----------

        Get dataset metadata.

        Parameters
        ----------

        ds_name : dataset name

        base_url_melodi : API Melodi URL - default production URL : "https://api.insee.fr/melodi"

        Returns
        -------

        List dataset metadata.

        Examples
        --------

        metadata=pynsee.get_metadata(ds_name = "DS_POPULATIONS_REFERENCE")

    get_range(
        ds_name: str,
        base_url_melodi: str = 'https://api.insee.fr/melodi',
        lang: str = 'fr',
        exclusions_list: list = ['GEO']
    ) -> pd.DataFrame
        Description
        ----------
        Get dataset range (codes and labels).
        Retrieves the list of dimensions and all their possible modalities values (codes and human-readable labels) for a given dataset.
        For GEO dimension, it is recommanded to used dedicated function : get_range_geo().

        Parameters
        ----------

        ds_name : dataset name

        base_url_melodi : API Melodi URL - default prod

        lang : french (fr) or english (en) labels - default french ("fr")

        exclusions_list : exclude some dimensions for a faster and light result - default : "GEO"

        Returns
        -------

        DataFrame with dimensions and modalities codes and labels

        Examples
        --------

        Example 1 :

        data=pynsee.get_range("DS_POPULATIONS_REFERENCE")

        data.info()
        data.head()

        Example 2 :

        data=pynsee.get_range(ds_name = "DS_EC_DECES",lang="en")

        data.info()
        data.head()

    get_range_geo(
        ds_name: str,
        base_url_melodi: str = 'https://api.insee.fr/melodi',
        lang: str = 'fr'
    ) -> pd.DataFrame
        Description
        ----------

        Get dataset's geography : codes and labels.
        Retrieves the list of geo dimensions and all their possible values (codes and human-readable labels) for a given dataset.

        Parameters
        ----------

        ds_name : dataset name

        base_url_melodi : API Melodi URL - default prod

        lang : french (fr) or english (en) labels - default french ("fr")

        Returns
        -------

        DataFrame with columns `GEO_REF`, `GEO_OBJECT`, `GEO_OBJECT_LABEL`, `GEO`, `GEO_LABEL`

        Examples
        --------

        Example 1 :

        data=pynsee.get_range_geo("DS_POPULATIONS_REFERENCE",lang="en")

        data.info()
        data.head()

        Example 2 :

        data=pynsee.get_range_geo("DS_TICM_PRATIQUES")

        data.info()
        data.head()

DATA
    __all__ = ['get_all_data', 'get_catalog', 'get_data', 'get_file', 'get...

FILE
    c:\insee\logicielsportables\appdata\roaming\python\python314\site-packages\pynsee\melodi\__init__.py

## V. Examples of function usage

### V.a get_all_data function : 

#### V.a.1 Help for get_all_data :

In [4]:
# Help for the get_all_data function of the melodi submodule
help(pynsee.get_all_data)

Help on function get_all_data in module pynsee.melodi.get_all_data:

get_all_data(
    ds_name: str,
    base_url_melodi: str = 'https://api.insee.fr/melodi',
    download_directory: str = None,
    stringsAsCategories: bool = False,
    remove_file: bool = True
)
    Description
    ----------

    Get all data from a dataset.

    Parameters
    ----------

    ds_name : dataset name - use get_ds_list to find a dataset identifier

    base_url_melodi : API Melodi URL - default production URL : "https://api.insee.fr/melodi"

    download_directory : download directory - default system tempdir

    stringsAsCategories : if TRUE, strings variables in DataFrame are converted to categories - default FALSE

    remove_file : remove downloaded data file after loading data - default TRUE

    Returns
    -------

    A tuple consisting of one DataFrame holding the data and another holding the metadata.

    Examples
    --------

    tuple=pynsee.get_all_data("DS_TICM_PRATIQUES")

    #data
    data=tuple[0]
    data.info()
    data.head()

    #metadata
    metadata=tuple[1]
    metadata.info()
    metadata.head()

#### V.a.2 Example of using get_all_data :

Example 1 :

In [5]:
# Tuple containing data and metadata for the dataset "DS_TICM_PRATIQUES"
tuple=pynsee.get_all_data("DS_TICM_PRATIQUES")

# Dataset for the DS : "DS_TICM_PRATIQUES"
data = tuple[0]
data.info()
data.head()

Request dataset: https://api.insee.fr/melodi/catalog/DS_TICM_PRATIQUES

 abstract :
 [{'content': 'Données sur les pratiques en ligne des personnes au niveau national.', 'lang': 'fr'}, {'content': 'Data on the online practices of individuals at the national level.', 'lang': 'en'}]

 accessRights :
 [{'content': 'Public', 'lang': 'fr'}, {'content': 'Public', 'lang': 'en'}]

 accrualPeriodicity :
 {'label': [{'content': 'Annuel', 'lang': 'fr'}, {'content': 'Annual', 'lang': 'en'}]}

 confidentialityStatus :
 [{'content': 'Libre', 'lang': 'fr'}, {'lang': 'en'}]

 creator :
 Insee

 description :
 [{'content': "Données annuelles sur les pratiques en ligne des personnes dont l'usage d'internet, la consultation d'un compte bancaire en ligne, les posts sur les réseaux sociaux, l'achat ou la vente en ligne.", 'lang': 'fr'}, {'content': 'Annual data on online practices of individuals, including internet usage, online banking account consultations, social media posts, and online buying or selling.', 'lang': 'en'}]

 identifier :
 DS_TICM_PRATIQUES

 issued :
 2024-11-15T10:15:09.000398052

 landingPage :
 [[{'lang': 'fr', 'url': ''}, {'lang': 'en', 'url': 'http://id.insee.fr/catalogues/jeuDeDonnees/decb7ef6-6c9a-4a38-8e33-eabb4d5056cd'}]]

 modified :
 2025-12-02T15:00:33.948948771

 numObservations :
 10336

 numSeries :
 0

 processStep :
 [{'content': 'inseeApi', 'lang': 'fr'}, {'content': 'inseeApi', 'lang': 'en'}]

 product :
 [{'accessURL': 'https://api.insee.fr/melodi/file/DS_TICM_PRATIQUES/DS_TICM_PRATIQUES_CSV_FR', 'byteSize': 65638, 'format': 'CSV', 'id': 'DS_TICM_PRATIQUES_CSV_FR', 'issued': '2025-12-02T14:11:39', 'language': 'FR', 'mediaType': 'text/csv', 'modified': '2026-05-18T13:32:23.026821934', 'packageFormat': 'application/zip', 'title': 'Pratiques en ligne des personnes '}]

 publisher :
 {'id': 'INSEE', 'label': [{'content': 'Institut national de la statistique et des etudes economiques (INSEE)', 'lang': 'fr'}, {'content': 'National Institute of Statistics and Economic Studies', 'lang': 'en'}]}

 relations :
 [{'title': [{'content': 'Insee Résultats', 'lang': 'fr'}, {'content': 'Insee Results', 'lang': 'en'}], 'titleComplement': [{'content': "L’usage des technologies de l'information et de la communication par les ménages entre 2009 et 2024 ", 'lang': 'fr'}, {'lang': 'en'}], 'url': [{'content': 'https://www.insee.fr/fr/statistiques/8670946', 'lang': 'fr'}, {'lang': 'en'}]}, {'title': [{'content': 'Documentation', 'lang': 'fr'}, {'content': 'Documentation', 'lang': 'en'}], 'titleComplement': [{'lang': 'fr'}, {'lang': 'en'}], 'url': [{'content': 'https://www.insee.fr/fr/metadonnees/source/operation/s2132/presentation', 'lang': 'fr'}, {'lang': 'en'}]}]

 scopeNote :
 [{'content': "L'enquête Technologies de l'information et de la communication auprès des ménages n'a pas été réalisée en 2020.\n\nDe nouveaux indicateurs sont disponibles et permettent de mesurer l’absence de contact par l’Internet avec une administration ou un service public selon l’âge.\nUne nouvelle série est créée à partir de 2025 : l’indicateur mesurant le « Taux de personnes ayant créé un profil ou posté sur les réseaux sociaux dans les 3 mois »  est remplacé par le « Taux de personnes ayant utilisé les réseaux sociaux dans les 3 mois » à compter de 2025.", 'lang': 'fr'}, {'content': 'The Information and Communication Technologies (ICT) survey of households was not conducted in 2020.', 'lang': 'en'}]

 spatial :
 {'id': 'FEHM', 'label': [{'content': 'France hors Mayotte', 'lang': 'fr'}, {'content': 'France excluding Mayotte', 'lang': 'en'}]}

 spatialResolution :
 [{'id': 'FRANCE', 'label': [{'content': 'France', 'lang': 'fr'}, {'content': 'France', 'lang': 'en'}]}]

 spatialTemporal :
 2025-01-01T01:00:00

 statisticalUnit :
 [{'label': [{'content': 'Ménage', 'lang': 'fr'}, {'content': 'Private household', 'lang': 'en'}]}]

 status :
 {'id': 'publie', 'label': [{'content': 'Publié', 'lang': 'fr'}, {'content': 'Completed', 'lang': 'en'}]}

 structure :
 {'dsd': 'DSD_TICM_PRATIQUES'}

 subtitle :
 [{'content': "Enquête Technologies de l'information et de la communication (TIC) auprès des ménages entre 2009 et 2025", 'lang': 'fr'}, {'content': 'Information and Communication Technologies (ICT) survey of households from 2009 to 2024', 'lang': 'en'}]

 temporal :
 {'endPeriod': '2025-01-01T00:00:00', 'startPeriod': '2009-01-01T00:00:00'}

 temporalResolution :
 [{'label': [{'content': 'Annuel', 'lang': 'fr'}, {'content': 'Annual', 'lang': 'en'}]}]

 theme :
 [{'label': [{'content': '3.3.3 Société de l’information', 'lang': 'fr'}, {'content': '3.3.3 Information society', 'lang': 'en'}], 'themeTaxonomy': 'classificationOfStatisticalDomain'}, {'label': [{'content': 'Consommation et équipement des ménages', 'lang': 'fr'}, {'content': 'Household consumption and ownership rates', 'lang': 'en'}], 'themeTaxonomy': 'inseeTheme'}]

 title :
 [{'content': 'Pratiques en ligne des personnes ', 'lang': 'fr'}, {'content': 'Internet use of individuals', 'lang': 'en'}]

 type :
 [{'content': 'Datacube', 'lang': 'fr'}, {'content': 'Datacube', 'lang': 'en'}]

 uri :
 http://id.insee.fr/catalogues/jeuDeDonnees/decb7ef6-6c9a-4a38-8e33-eabb4d5056cd

 uuid :
 3ad4e284-89b5-9fc7-1a91-2b52519cbe58

 wasGeneratedBy :
 [{'id': 's1275', 'label': [{'content': "Enquête annuelle auprès des ménages sur les technologies de l'information et de la communication", 'lang': 'fr'}, {'content': 'Household annual survey on information and communication technologies', 'lang': 'en'}]}, {'id': 's10', 'label': [{'content': "Technologies de l'information et de la communication", 'lang': 'fr'}, {'content': 'Information and Communication Technologies', 'lang': 'en'}]}]
Request ZIP CSV file : https://api.insee.fr/melodi/file/DS_TICM_PRATIQUES/DS_TICM_PRATIQUES_CSV_FR

Downloading the file: 65.6kB [00:00, 2.51MB/s]

Listing of files : ['DS_TICM_PRATIQUES_metadata.csv', 'DS_TICM_PRATIQUES_data.csv']
Remove downloaded files.
<class 'pandas.DataFrame'>
RangeIndex: 10336 entries, 0 to 10335
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   TICM_MEASURE  10336 non-null  str
 1   FREQ          10336 non-null  str
 2   SEX           10336 non-null  str
 3   AGE           10336 non-null  str
 4   EDUC          10336 non-null  str
 5   EMPSTA        10336 non-null  str
 6   PCS_ESE       10336 non-null  str
 7   OBS_STATUS    10336 non-null  str
 8   TIME_PERIOD   10336 non-null  int64
 9   OBS_VALUE     6118 non-null   float64
dtypes: float64(1), int64(1), str(8)
memory usage: 1.0 MB

,TICM_MEASURE,FREQ,SEX,AGE,EDUC,EMPSTA,PCS_ESE,OBS_STATUS,TIME_PERIOD,OBS_VALUE
0,EMAIL,A,_T,_T,_T,1,4,L,2010,NaN
1,EMAIL,A,_T,_T,_T,1,5,L,2015,NaN
2,EMAIL,A,_T,_T,_T,1,5,L,2017,NaN
3,EMAIL,A,_T,_T,_T,1,3,L,2018,NaN
4,EMAIL,A,_T,_T,_T,_T,_T,L,2017,NaN

In [6]:
# Metadata for DS : "DS_TICM_PRATIQUES"
metadata = tuple[1]
metadata.info()
metadata.head()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   COD_VAR     60 non-null     str
 1   LIB_VAR     60 non-null     str
 2   COD_MOD     60 non-null     str
 3   LIB_MOD     60 non-null     str
 4   GEO_OBJECT  0 non-null      float64
dtypes: float64(1), str(4)
memory usage: 7.5 KB

  COD_VAR LIB_VAR COD_MOD         LIB_MOD  GEO_OBJECT
0     AGE     Âge  Y15T29  De 15 à 29 ans         NaN
1     AGE     Âge  Y30T44  De 30 à 44 ans         NaN
2     AGE     Âge  Y45T59  De 45 à 59 ans         NaN
3     AGE     Âge  Y60T74  De 60 à 74 ans         NaN
4     AGE     Âge  Y_GE75  75 ans ou plus         NaN

Example 2 :

In [7]:
# Tuple containing data and metadata for the dataset "DS_FILOSOFI_CC"
tuple=pynsee.get_all_data("DS_FILOSOFI_CC")

# Dataset for the DS : "DS_FILOSOFI_CC"
data = tuple[0]
data.info()
data.head()

Request dataset: https://api.insee.fr/melodi/catalog/DS_FILOSOFI_CC

 abstract :
 [{'content': 'Niveau de vie, taux de pauvreté et décomposition du revenu disponible.\nLe niveau de vie médian et le taux de pauvreté sont disponibles du niveau communal à la France Métropolitaine.\nLes autres indicateurs sont disponibles uniquement pour les départements, les régions et la France métropolitaine.\n\n', 'lang': 'fr'}, {'content': 'Standard of living, poverty rate, and breakdown of disposable income. The median standard of living and the poverty rate are available from the municipal level up to Metropolitan France. Other indicators are only available for departments, regions, and Metropolitan France.', 'lang': 'en'}]

 accessRights :
 [{'content': 'Public', 'lang': 'fr'}, {'content': 'Free', 'lang': 'en'}]

 accrualPeriodicity :
 {'label': [{'content': 'Annuel', 'lang': 'fr'}, {'content': 'Annual', 'lang': 'en'}]}

 confidentialityStatus :
 [{'content': 'Libre', 'lang': 'fr'}, {'content': 'Free', 'lang': 'en'}]

 creator :
 Insee

 description :
 [{'content': 'Indicateurs aux niveaux département, région et France métropolitaine :\n- Déciles du niveau de vie (du 1er au 9e)\n- Quartiles du niveau de vie (1er et 3e)\n- Médiane du niveau de vie\n- Taux de pauvreté à 60 % du niveau de vie médian de la France métropolitaine\n- Rapport interdécile (D9/D1)\n- Ecart interquartile (Q3-Q1)\n- Indice de Gini\n- Rapport des masses (S80/S20)\n- Décomposition du revenu disponible\n\nIndicateurs aux niveaux établissement public de coopération intercommunale (EPCI), établissement public territorial (EPT), collectivité territoriale à compétences départementales (CTCD), commune, arrondissement municipal, arrondissement, aire d’attraction des villes 2020, bassin de vie 2022, unité urbaine 2020, zone d’emploi 2020 :\n- Médiane du niveau de vie\n- Taux de pauvreté à 60 % du niveau de vie médian de la France métropolitaine\n\nLes indicateurs sont calculés sur le champ des personnes appartenant à des ménages fiscaux dont le revenu disponible est positif ou nul.\n\nLes résultats couvrent la France métropolitaine et La Réunion.', 'lang': 'fr'}, {'content': 'Indicators at the département, regional and metropolitan France levels :\n- Deciles of standard of living (from the 1st to the 9th)\n- Quartiles of standard of living (1st and 3rd)\n- Median standard of living\n- Poverty rate at 60% of the median\n- Interdecile ratio (D9/D1)\n- Interquartile range (Q3–Q1),\n- Gini coefficient\n- Income share ratio (S80/S20)\n- Breakdown of disposable income\n\nIndicators at the levels of inter-municipal public cooperation establishments (EPCI), territorial public establishments (EPT), territorial authorities with département-level powers (CTCD), municipalities, municipal arrondissements, arrondissements, 2020 functional urban areas, 2022 living areas, 2020 urban units, and 2020 employment areas :\n- Median standard of living\n- Poverty rate at 60% of the median standard of living in metropolitan France\n\nThe indicators are calculated for individuals belonging to tax households with non-negative disposable income.\n\nThe results cover metropolitan France and La Réunion.', 'lang': 'en'}]

 identifier :
 DS_FILOSOFI_CC

 issued :
 2026-05-01T14:31:06.000815005

 keyword :
 [{'label': [{'content': 'Niveau de vie', 'lang': 'fr'}, {'content': 'Standard of living', 'lang': 'en'}]}, {'label': [{'content': 'Taux de pauvreté', 'lang': 'fr'}, {'content': 'Poverty threshold', 'lang': 'en'}]}]

 landingPage :
 [[{'lang': 'fr', 'url': ''}, {'lang': 'en', 'url': ''}]]

 modified :
 2026-08-06T13:34:40.757936971

 numObservations :
 1123173

 numSeries :
 0

 ordreComposants :
 ['TIME_PERIOD', 'GEO', 'FILOSOFI_MEASURE', 'OBS_VALUE', 'UNIT_MEASURE', 'UNIT_MULT', 'CONF_STATUS', 'OBS_STATUS']

 processStep :
 [{'content': 'inseeApi', 'lang': 'fr'}, {'content': 'inseeApi', 'lang': 'en'}]

 product :
 [{'accessURL': 'https://api.insee.fr/melodi/file/DS_FILOSOFI_CC/DS_FILOSOFI_CC_2023_CSV_FR', 'byteSize': 5352911, 'format': 'CSV', 'id': 'DS_FILOSOFI_CC_2023_CSV_FR', 'issued': '2026-08-06T13:29:20.396407589', 'language': 'FR', 'mediaType': 'text/csv', 'modified': '2026-08-06T13:29:20.396407589', 'packageFormat': 'application/zip', 'title': 'Niveau de vie, taux de pauvreté, décomposition du revenu disponible en 2023'}, {'accessURL': 'https://api.insee.fr/melodi/file/DS_FILOSOFI_CC/FILOSOFI_CC_2023_FR', 'byteSize': 1284610, 'format': 'XLSX', 'id': 'FILOSOFI_CC_2023_FR', 'issued': '2026-08-06T13:25:16.430405164', 'language': 'FR', 'mediaType': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'modified': '2026-08-06T13:25:16.430405164', 'title': "Niveau de vie, taux de pauvreté, indicateurs d'inégalités et décomposition du revenu disponible par zonage en 2023"}]

 publisher :
 {'id': 'INSEE', 'label': [{'content': 'Institut national de la statistique et des etudes economiques (INSEE)', 'lang': 'fr'}, {'content': 'National Institute of Statistics and Economic Studies', 'lang': 'en'}]}

 raccourcis :
 [{'description': {'en': '', 'fr': ''}, 'raccourcis': [{'choix': ['D1_SL', 'D2_SL', 'D3_SL', 'D4_SL', 'D6_SL', 'D7_SL', 'D8_SL', 'D9_SL', 'MED_SL', 'Q1_SL', 'Q3_SL'], 'idComponent': 'FILOSOFI_MEASURE'}], 'titre': {'en': 'Distribution of standard of living', 'fr': 'Distribution du niveau de vie'}}, {'description': {'en': '', 'fr': ''}, 'raccourcis': [{'choix': ['GI_SL', 'IQR_SL', 'IR_D9_D1_SL', 'S80S20_SL'], 'idComponent': 'FILOSOFI_MEASURE'}], 'titre': {'en': 'Inequality indicators', 'fr': "Indicateurs d'inégalités"}}, {'description': {'en': '', 'fr': ''}, 'raccourcis': [{'choix': ['PR_MD60'], 'idComponent': 'FILOSOFI_MEASURE'}], 'titre': {'en': 'Poverty rate', 'fr': 'Taux de pauvreté'}}, {'description': {'en': '', 'fr': ''}, 'raccourcis': [{'choix': ['S_DIR_TAX_DI', 'S_EI_DI', 'S_EI_DI_N_SAL', 'S_EI_DI_SAL', 'S_EI_DI_UNE', 'S_INC_ASS_DI', 'S_RET_PEN_DI', 'S_SOC_BEN_DI', 'S_SOC_BEN_DI_FAM_BEN', 'S_SOC_BEN_DI_HOU_BEN', 'S_SOC_BEN_DI_MIN_SOC'], 'idComponent': 'FILOSOFI_MEASURE'}], 'titre': {'en': 'Composition of disposable income', 'fr': 'Décomposition du revenu disponible'}}]

 relations :
 [{'title': [{'content': 'Documentation', 'lang': 'fr'}, {'content': 'Documentation', 'lang': 'en'}], 'titleComplement': [{'content': ": note d'accompagnement Filosofi 2023", 'lang': 'fr'}, {'lang': 'en'}], 'url': [{'content': 'https://www.insee.fr/fr/statistiques/fichier/8984748/Note_accompagnement_Filosofi_2023.pdf', 'lang': 'fr'}, {'lang': 'en'}]}, {'title': [{'content': 'Insee Résultats', 'lang': 'fr'}, {'content': 'Insee Results', 'lang': 'en'}], 'titleComplement': [{'content': ': principaux résultats sur les revenus et la pauvreté des ménages en 2023', 'lang': 'fr'}, {'lang': 'en'}], 'url': [{'content': 'https://www.insee.fr/fr/statistiques/8984758', 'lang': 'fr'}, {'lang': 'en'}]}]

 scopeNote :
 [{'content': 'Le millésime 2023 de Filosofi est le dernier disponible. Compte tenu des changements méthodologiques introduits, les indicateurs 2023 issus du dispositif Filosofi 2 ne sont pas directement comparables avec les indicateurs issus de Filosofi (millésimes 2012 à 2021).\n\n06/08/2026 – Diffusion complémentaire des taux de pauvreté et géographie de diffusion\n\nUne erreur technique avait conduit à ne pas diffuser le taux de pauvreté pour un nombre important de territoires alors que cet indicateur aurait dû être publié. Celle-ci est à présent corrigée. Les autres données déjà diffusées restent correctes et ne sont pas affectées. Par ailleurs, les données sont désormais directement établies selon le référentiel géographique en vigueur au 1ᵉʳ janvier 2026.\n\nPrécisions sur les périmètres géographiques\xa0:\n\n- Les données ne sont pas disponibles pour les communes de Celles (15031), Chalinargues (15035), Chavagnac (15047) et Sainte-Anastasie (15171). Elles sont incluses dans celles de la commune des Neussargues-Moissac (15141).\n\n- Pour les communes de l’Oie (85165) et de Sainte-Florence (85212) et pour l’unité urbaine de Sainte-Florence (85139) qu’elles constituent, les données sont respectivement intégrées à la commune d’Essarts-en-Bocage (85084) et à l’unité urbaine d’Essarts-en-Bocage (85213). \n\n- Les données de la commune de Suzan (09304), qui constitue une enclave, sont intégrées à celles de la commune de La-Bastide-de-Sérou (09042). \n', 'lang': 'fr'}, {'content': "The 2023 Filosofi dataset is the latest available. Given the methodological changes introduced, the 2023 indicators derived from the Filosofi 2 system are not directly comparable with those derived from Filosofi (vintages 2012 to 2021).\n\nThe data are disseminated according to the geographic reference framework in force as of January 1, 2026.\n\n06/08/2026 – Supplementary release of poverty rates and dissemination geography\nA technical error had led to the poverty rate not being published for a significant number of territories, even though this indicator should have been released. This has now been corrected. Other previously published data remain correct and are unaffected. Furthermore, the data is now directly produced using the official geographic framework in effect as of January 1, 2026.\n\nDetails on geographic scope :\n\n- Data are not available for the municipalities (communes) of Celles (15031), Chalinargues (15035), Chavagnac (15047), and Sainte-Anastasie (15171). They are included in the data for the municipality of Neussargues-Moissac (15141).\n\n- For the municipalities of L'Oie (85165) and Sainte-Florence (85212), and for the urban unit (unité urbaine) of Sainte-Florence (85139) which they form, data are respectively integrated into the municipality of Essarts-en-Bocage (85084) and the urban unit of Essarts-en-Bocage (85213).\n\n- Data for the municipality of Suzan (09304), which constitutes an enclave, are integrated into those of the municipality of La Bastide-de-Sérou (09042).", 'lang': 'en'}]

 spatial :
 {'id': 'FMR', 'label': [{'content': 'France métropolitaine et La Réunion', 'lang': 'fr'}, {'content': 'Metropolitan France and Réunion', 'lang': 'en'}]}

 spatialResolution :
 [{'id': 'AAV2020', 'label': [{'content': "Aire d'attraction des villes 2020", 'lang': 'fr'}, {'content': 'Functional area', 'lang': 'en'}]}, {'id': 'ARR', 'label': [{'content': 'Arrondissement', 'lang': 'fr'}, {'content': 'District', 'lang': 'en'}]}, {'id': 'ARM', 'label': [{'content': 'Arrondissement municipal', 'lang': 'fr'}, {'content': 'Municipal district', 'lang': 'en'}]}, {'id': 'OTHER', 'label': [{'content': 'Autre type de territoires', 'lang': 'fr'}, {'content': 'Other types of territories', 'lang': 'en'}]}, {'id': 'BV2022', 'label': [{'content': 'Bassin de vie 2022', 'lang': 'fr'}, {'content': 'Commuter belt', 'lang': 'en'}]}, {'id': 'COM', 'label': [{'content': 'Commune', 'lang': 'fr'}, {'content': 'Commune', 'lang': 'en'}]}, {'id': 'DEP', 'label': [{'content': 'Département', 'lang': 'fr'}, {'content': 'Department', 'lang': 'en'}]}, {'id': 'EPCI', 'label': [{'content': 'Etablissement public de coopération intercommunal', 'lang': 'fr'}, {'content': 'Intercommunal cooperation public Establishment', 'lang': 'en'}]}, {'id': 'FRANCE', 'label': [{'content': 'France', 'lang': 'fr'}, {'content': 'France', 'lang': 'en'}]}, {'id': 'REG', 'label': [{'content': 'Région', 'lang': 'fr'}, {'content': 'Region', 'lang': 'en'}]}, {'id': 'UU2020', 'label': [{'content': 'Unité urbaine 2020', 'lang': 'fr'}, {'content': 'Urban unit', 'lang': 'en'}]}, {'id': 'ZE2020', 'label': [{'content': "Zones d'emploi 2020", 'lang': 'fr'}, {'content': 'Employment zone', 'lang': 'en'}]}]

 spatialTemporal :
 2026-01-01T01:00:00

 statisticalUnit :
 [{'label': [{'content': 'Individu', 'lang': 'fr'}, {'content': 'Person', 'lang': 'en'}]}]

 status :
 {'id': 'publie', 'label': [{'content': 'Publié', 'lang': 'fr'}, {'content': 'Completed', 'lang': 'en'}]}

 structure :
 {'dsd': 'DSD_FILOSOFI2_CC'}

 subtitle :
 [{'content': 'Revenus localisés sociaux et fiscaux (Filosofi 2)', 'lang': 'fr'}, {'content': 'Localized social and fiscal income (Filosofi 2)', 'lang': 'en'}]

 temporal :
 {'endPeriod': '2023-01-01T00:00:00', 'startPeriod': '2023-01-01T00:00:00'}

 temporalResolution :
 [{'label': [{'content': 'Annuel', 'lang': 'fr'}, {'content': 'Annual', 'lang': 'en'}]}]

 theme :
 [{'label': [{'content': '3.4 Revues annuelles et recueils', 'lang': 'fr'}, {'content': '3.4 Yearbooks and similar compendia ', 'lang': 'en'}], 'themeTaxonomy': 'classificationOfStatisticalDomain'}, {'label': [{'content': '3. Environnement et statistiques multi-domaines', 'lang': 'fr'}, {'content': '3 Environment and multi-domain statistics', 'lang': 'en'}], 'themeTaxonomy': 'classificationOfStatisticalDomain'}, {'label': [{'content': '1.5 Revenu et consommation', 'lang': 'fr'}, {'content': '1.5 Income and consumption', 'lang': 'en'}], 'themeTaxonomy': 'classificationOfStatisticalDomain'}, {'label': [{'content': '1. Statistiques démographiques et sociales', 'lang': 'fr'}, {'content': '1. Demographic and social statistics', 'lang': 'en'}], 'themeTaxonomy': 'classificationOfStatisticalDomain'}, {'label': [{'content': "Revenus – Niveaux de vie – Pouvoir d'achat", 'lang': 'fr'}, {'content': 'Income – Living standards – Purchasing power', 'lang': 'en'}], 'themeTaxonomy': 'inseeTheme'}, {'label': [{'content': 'Pauvreté – Précarité', 'lang': 'fr'}, {'content': 'Poverty –\xa0precarity', 'lang': 'en'}], 'themeTaxonomy': 'inseeTheme'}]

 title :
 [{'content': 'Niveau de vie, taux de pauvreté, décomposition du revenu disponible en 2023', 'lang': 'fr'}, {'content': 'Standard of living, poverty rate, and composition of disposable income in 2023', 'lang': 'en'}]

 type :
 [{'content': 'Datacube', 'lang': 'fr'}, {'content': 'Aggregated data', 'lang': 'en'}]

 uri :
 http://id.insee.fr/catalogues/jeuDeDonnees/de58c428-4c44-4873-a2bb-4583896b12a6

 uuid :
 917e2025-5fc1-48f8-93f8-62008000db82

 wasGeneratedBy :
 [{'id': 's2286', 'label': [{'content': 'Revenus localisés sociaux et fiscaux 2023', 'lang': 'fr'}, {'content': 'Social and fiscal localized income 2023', 'lang': 'en'}]}, {'id': 's1172', 'label': [{'content': 'Revenus localisés sociaux et fiscaux', 'lang': 'fr'}, {'content': 'Social and fiscal localized income', 'lang': 'en'}]}, {'id': 's66', 'label': [{'content': 'Revenus localisés', 'lang': 'fr'}, {'content': 'Localized incomes', 'lang': 'en'}]}]
Request ZIP CSV file : https://api.insee.fr/melodi/file/DS_FILOSOFI_CC/DS_FILOSOFI_CC_2023_CSV_FR

Downloading the file: 5.35MB [00:01, 4.50MB/s]

Listing of files : ['DS_FILOSOFI_CC_2023_data.csv', 'DS_FILOSOFI_CC_2023_metadata.csv']

C:\INSEE\LogicielsPortables\AppData\Roaming\Python\Python314\site-packages\pynsee\melodi\get_all_data.py:113: DtypeWarning: Columns (0: GEO) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(filepath_or_buffer=file_data,sep=";",decimal=".")#importer le fichier csv en DataFrame

Remove downloaded files.
<class 'pandas.DataFrame'>
RangeIndex: 1123173 entries, 0 to 1123172
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   GEO               1123173 non-null  object
 1   GEO_OBJECT        1123173 non-null  str
 2   FILOSOFI_MEASURE  1123173 non-null  str
 3   UNIT_MEASURE      1123173 non-null  str
 4   UNIT_MULT         1123173 non-null  int64
 5   CONF_STATUS       1123173 non-null  str
 6   OBS_STATUS        1123173 non-null  str
 7   TIME_PERIOD       1123173 non-null  int64
 8   OBS_VALUE         52457 non-null    float64
dtypes: float64(1), int64(2), object(1), str(5)
memory usage: 96.6+ MB

,GEO,GEO_OBJECT,FILOSOFI_MEASURE,UNIT_MEASURE,UNIT_MULT,CONF_STATUS,OBS_STATUS,TIME_PERIOD,OBS_VALUE
0,EPT_200057875,OTHER,S_DIR_TAX_DI,PT,0,F,O,2023,NaN
1,EPT_200058006,OTHER,S_SOC_BEN_DI_HOU_BEN,PT,0,F,O,2023,NaN
2,EPT_200057982,OTHER,D2_SL,EUR_YR,0,F,O,2023,NaN
3,EPT_200058790,OTHER,GI_SL,NR,0,F,O,2023,NaN
4,EPT_200058014,OTHER,D8_SL,EUR_YR,0,F,O,2023,NaN

In [8]:
# Metadata for DS : "DS_FILOSOFI_CC"
metadata = tuple[1]
metadata.info()
metadata.head()

<class 'pandas.DataFrame'>
RangeIndex: 41647 entries, 0 to 41646
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   COD_VAR     41647 non-null  str
 1   LIB_VAR     41647 non-null  str
 2   COD_MOD     41647 non-null  str
 3   LIB_MOD     41647 non-null  str
 4   GEO_OBJECT  41599 non-null  str
dtypes: str(5)
memory usage: 3.0 MB

,COD_VAR,LIB_VAR,COD_MOD,LIB_MOD,GEO_OBJECT
0,CONF_STATUS,Statut de confidentialité,F,Diffusable,NaN
1,CONF_STATUS,Statut de confidentialité,C,Confidentiel (secret statistique),NaN
2,FILOSOFI_MEASURE,Mesures filosofi,D1_SL,1er décile du niveau de vie (en euros),NaN
3,FILOSOFI_MEASURE,Mesures filosofi,D2_SL,2e décile du niveau de vie (en euros),NaN
4,FILOSOFI_MEASURE,Mesures filosofi,D3_SL,3e décile du niveau de vie (en euros),NaN

### V.b get_catalog function : 

#### V.b.1 Help for get_catalog :

In [9]:
# Help for the get_catalog function of the melodi submodule
help(pynsee.get_catalog)

Help on function get_catalog in module pynsee.melodi.get_catalog:

get_catalog(
    lang: str = 'fr',
    base_url_melodi: str = 'https://api.insee.fr/melodi'
) -> pd.DataFrame
    Description
    ----------

    Get list of available datasets.

    Parameters
    ----------

    lang : str, {"fr", "en"}, default "fr"
        Language of metadata.

    base_url_melodi : str, default "https://api.insee.fr/melodi"
        Base URL of the Melodi API.

    Returns
    -------

    DataFrame with columns: identifier, title_content,
    subtitle_content, description_content, abstract_content,
    temporal_startPeriod, temporal_endPeriod, modified,
    numObservations, numSeries.

    Raises
    ------

    ValueError
        If ``lang`` is not 'fr' or 'en'.

    Examples
    --------
    Example 1: Get the catalog in French (default)

    catalogue_melodi = pynsee.get_catalog()
    catalogue_melodi.head()

    Example 2: Get the catalog in English

    catalogue_melodi = pynsee.get_catalog(lang="en")
    catalogue_melodi.head()

#### V.b.2 Examples of using get_catalog :

Example 1 :

In [10]:
# Extract and display the catalog of available datasets in the Melodi catalog
catalogue_melodi = pynsee.get_catalog()
catalogue_melodi.head()

Catalog request : https://api.insee.fr/melodi/catalog/all

,identifier,title_content,subtitle_content,description_content,abstract_content,temporal_startPeriod,temporal_endPeriod,modified,numObservations,numSeries
0,DD_CNA_AGREGATS,Produit Intérieur Brut (PIB) et grands agrégat...,Comptes nationaux annuels - Base 2020,Le produit intérieur brut (PIB) est le princip...,Données annuelles de Produit Intérieur Brut (P...,1949-01-01T00:00:00,2025-01-01T00:00:00,2026-08-31T15:53:44.131033164,228727,3672
1,DD_CNA_APU,Comptes des administrations publiques,Comptes nationaux annuels - Base 2020,Le secteur institutionnel des administrations ...,Données concernant le secteur institutionnel d...,1949-01-01T00:00:00,2025-01-01T00:00:00,2026-08-31T15:11:41.507130921,627596,21455
2,DD_CNA_BRANCHES,Activité des branches de l'économie,Comptes nationaux annuels - Base 2020,Données annuelles sur l'activité des branches ...,Données annuelles sur l'activité des branches ...,1949-01-01T00:00:00,2025-01-01T00:00:00,2026-08-31T15:44:44.067464852,444052,9272
3,DD_CNA_CONSO_MENAGES_COICOP,Consommation des ménages par fonction,Comptes nationaux annuels - Base 2020,Données annuelles de consommation finale effec...,Données annuelles de consommation finale effec...,1949-01-01T00:00:00,2025-01-01T00:00:00,2026-08-31T15:50:44.122734411,258305,3896
4,DD_CNA_CONSO_MENAGES_PRODUITS,Consommation des ménages par produit,Comptes nationaux annuels - Base 2020,Données annuelles de consommation finale effec...,Données annuelles de consommation finale effec...,1949-01-01T00:00:00,2025-01-01T00:00:00,2026-08-31T14:47:40.530574921,1032294,0

Example 2 :

In [11]:
# Extract and display the catalog of datasets available in the Melodi catalog in English
catalogue_melodi = pynsee.get_catalog(lang="en")
catalogue_melodi.head()

Catalog request : https://api.insee.fr/melodi/catalog/all

,identifier,title_content,subtitle_content,description_content,abstract_content,temporal_startPeriod,temporal_endPeriod,modified,numObservations,numSeries
0,DD_CNA_AGREGATS,Gross domestic product (GDP) and main economic...,Base 2020 - Annual Results,Gross domestic product (GDP) is the main aggre...,Annual data on Gross Domestic Product (GDP) an...,1949-01-01T00:00:00,2025-01-01T00:00:00,2026-08-31T15:53:44.131033164,228727,3672
1,DD_CNA_APU,General government accounts,Annual national accounts - Base 2020,The general government sector is broken down i...,Data dealing with the public administration in...,1949-01-01T00:00:00,2025-01-01T00:00:00,2026-08-31T15:11:41.507130921,627596,21455
2,DD_CNA_BRANCHES,Production and generation of income by industry,National accounts - Base 2020,Annual data on the activity of industries as r...,Annual data on the activity of branches within...,1949-01-01T00:00:00,2025-01-01T00:00:00,2026-08-31T15:44:44.067464852,444052,9272
3,DD_CNA_CONSO_MENAGES_COICOP,Households consumption by fonction,National accounts - Base 2020,Annual data on actual household final consumpt...,Annual data on actual final household consumpt...,1949-01-01T00:00:00,2025-01-01T00:00:00,2026-08-31T15:50:44.122734411,258305,3896
4,DD_CNA_CONSO_MENAGES_PRODUITS,Household consumption in products,National accounts - Base 2020,Annual data on actual household final consumpt...,Annual data on actual final household consumpt...,1949-01-01T00:00:00,2025-01-01T00:00:00,2026-08-31T14:47:40.530574921,1032294,0

### V.c get_data function : 

#### V.c.1 Help for get_data :

In [12]:
# Help for the get_data function of the melodi submodule
help(pynsee.get_data)

Help on function get_data in module pynsee.melodi.get_data:

get_data(url: str) -> pd.DataFrame
    Description
    ----------

    Get Melodi data by URL.
    URL parameter can be copied/pasted from explorer https://catalogue-donnees.insee.fr.

    Parameters
    ----------

    url : URL API data Melodi - Start by "https://api.insee.fr/melodi/data/..."

    Returns
    -------

    DataFrame with data.

    Examples
    --------

    data=pynsee.get_data("https://api.insee.fr/melodi/data/DS_POPULATIONS_REFERENCE?POPREF_MEASURE=PMUN&GEO=FRANCE-F")

    data.info()
    data.head()

#### V.c.2 Examples of using get_data :

Example 1 :

In [13]:
# Extract and display data for the dataset "DS_POPULATIONS_REFERENCE" selecting the measure "PMUN" and territory "FRANCE-F"
data=pynsee.get_data("https://api.insee.fr/melodi/data/DS_POPULATIONS_REFERENCE?POPREF_MEASURE=PMUN&GEO=FRANCE-F")

data.info()
data.head()

Total count request : https://api.insee.fr/melodi/data/DS_POPULATIONS_REFERENCE?POPREF_MEASURE=PMUN&GEO=FRANCE-F&totalCount=TRUE&maxResult=0
Number of lines : 1
<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GEO_REF         1 non-null      object
 1   GEO_OBJECT      1 non-null      object
 2   GEO             1 non-null      object
 3   TIME_PERIOD     1 non-null      str
 4   FREQ            1 non-null      str
 5   POPREF_MEASURE  1 non-null      str
 6   OBS_VALUE       1 non-null      float64
dtypes: float64(1), object(3), str(3)
memory usage: 197.0+ bytes

  GEO_REF GEO_OBJECT GEO TIME_PERIOD FREQ POPREF_MEASURE   OBS_VALUE
0    2025     FRANCE   F        2023    A           PMUN  68094280.0

Example 2 :

In [14]:
# Extract and display data for the dataset "DS_RP_MENAGES_PRINC_IRIS" selecting the measure "POP", civil status "_T", household size "_T", and age "Y_GE15"
data=pynsee.get_data("https://api.insee.fr/melodi/data/DS_RP_MENAGES_PRINC_IRIS?RP_MEASURE=POP&CIVIL_STATUS=_T&NOC=_T&AGE=Y_GE15")

data.info()
data.head()

Total count request : https://api.insee.fr/melodi/data/DS_RP_MENAGES_PRINC_IRIS?RP_MEASURE=POP&CIVIL_STATUS=_T&NOC=_T&AGE=Y_GE15&totalCount=TRUE&maxResult=0
Number of lines : 49,219
<class 'pandas.DataFrame'>
RangeIndex: 49219 entries, 0 to 49218
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GEO_REF         49219 non-null  object
 1   GEO_OBJECT      49219 non-null  object
 2   GEO             49219 non-null  object
 3   TIME_PERIOD     49219 non-null  str
 4   CIVIL_STATUS    49219 non-null  str
 5   LARGE_DISTRICT  49219 non-null  str
 6   NOC             49219 non-null  str
 7   TYP_IRIS        49219 non-null  str
 8   FREQ            49219 non-null  str
 9   RP_MEASURE      49219 non-null  str
 10  TRIRIS          49219 non-null  str
 11  OCS             49219 non-null  str
 12  LAB_IRIS        49219 non-null  str
 13  AGE             49219 non-null  str
 14  OBS_STATUS      49219 non-null  str
 15  OBS_VALUE       49219 non-null  float64
dtypes: float64(1), object(3), str(12)
memory usage: 7.7+ MB

,GEO_REF,GEO_OBJECT,GEO,TIME_PERIOD,CIVIL_STATUS,LARGE_DISTRICT,NOC,TYP_IRIS,FREQ,RP_MEASURE,TRIRIS,OCS,LAB_IRIS,AGE,OBS_STATUS,OBS_VALUE
0,2025,COM,01001,2023,_T,ZZZZZZ,_T,Z,A,POP,ZZZZZZ,_T,5,Y_GE15,A,699.19487
1,2025,COM,01002,2023,_T,ZZZZZZ,_T,Z,A,POP,ZZZZZZ,_T,5,Y_GE15,A,214.19188
2,2025,COM,01005,2023,_T,ZZZZZZ,_T,Z,A,POP,ZZZZZZ,_T,5,Y_GE15,A,1553.97385
3,2025,COM,01006,2023,_T,ZZZZZZ,_T,Z,A,POP,ZZZZZZ,_T,5,Y_GE15,A,104.91228
4,2025,COM,01007,2023,_T,ZZZZZZ,_T,Z,A,POP,ZZZZZZ,_T,5,Y_GE15,A,2269.07667

### V.d get_file function : 

#### V.d.1 Aide de get_file :

In [15]:
# Help for the get_file function of the melodi submodule
help(pynsee.get_file)

Help on function get_file in module pynsee.melodi.get_file:

get_file(
    ds_name: str,
    download_file_name: str = None,
    file_name: str = None,
    download_directory: str = None,
    base_url_melodi: str = 'https://api.insee.fr/melodi'
) -> str
    Description
    ----------

    Get file attached to a dataset : extract (XLSX), or full CSV file, or full parquet file.

    Parameters
    ----------

    ds_name : dataset name

    file_name : file name, optional. Omit this parameter to get the Parquet file

    download_file_name : filename on disk after download, optional. Omit this parameter to get the Parquet file

    download_directory : download directory - default system tempdir

    base_url_melodi : API Melodi URL - default production URL : "https://api.insee.fr/melodi"

    Returns
    -------

    The path of the downloaded file.

    Examples
    --------

    Example 1 : download the XLSX associated with a dataset

    pynsee.get_file(ds_name = "DS_EC_DECES",
             file_name = "T1_DECES_JOUR_NAT_FR",
             download_file_name = "T1_DECES_JOUR_NAT_FR.xlsx")

    Example 2 : download the CSV in an archive that corresponds to the dataset

    pynsee.get_file(ds_name = "DS_EC_DECES",
             file_name = "DS_EC_DECES_CSV_FR",
             download_file_name = "DS_EC_DECES_CSV_FR.zip")

    Example 3 : download the parquet file that corresponds to the dataset

    pynsee.get_file(ds_name = "DS_RP_SERIE_HISTORIQUE")

#### V.d.2 Examples of using get_file :

Example 1 : xlsx file named BPE_SPORT_LOISIR_CULTURE_FR associated with the dataset DS_BPE

In [16]:
# Download the excel file named "BPE_SPORT_LOISIR_CULTURE_FR" from the dataset "DS_BPE" and save it as "BPE_SPORT_LOISIR_CULTURE_FR.xlsx"
pynsee.get_file(ds_name = "DS_BPE",
             file_name = "BPE_SPORT_LOISIR_CULTURE_FR",
             download_file_name = "BPE_SPORT_LOISIR_CULTURE_FR.xlsx")

Request file : https://api.insee.fr/melodi/file/DS_BPE/BPE_SPORT_LOISIR_CULTURE_FR
Downloaded path : C:\Users\HRTQL2\AppData\Local\Temp\BPE_SPORT_LOISIR_CULTURE_FR.xlsx

'C:\\Users\\HRTQL2\\AppData\\Local\\Temp\\BPE_SPORT_LOISIR_CULTURE_FR.xlsx'

Example 2 : CSV file associated with the DS "DS_FILOSOFI_SAGE_LOG_TP_NIVVIE"

In [17]:
# Download the CSV file associated with the DS "DS_FILOSOFI_SAGE_LOG_TP_NIVVIE", named "DS_FILOSOFI_SAGE_LOG_TP_NIVVIE_2023_CSV_FR" and save it as "DS_FILOSOFI_SAGE_LOG_TP_NIVVIE_CSV_FR.zip" which contains a data file and a metadata file
# The data file corresponds to the entire database and the metadata file corresponds to the description of variables and modalities
pynsee.get_file(ds_name = "DS_FILOSOFI_SAGE_LOG_TP_NIVVIE",
             file_name = "DS_FILOSOFI_SAGE_LOG_TP_NIVVIE_2023_CSV_FR",
             download_file_name = "DS_FILOSOFI_SAGE_LOG_TP_NIVVIE_CSV_FR.zip")

Request file : https://api.insee.fr/melodi/file/DS_FILOSOFI_SAGE_LOG_TP_NIVVIE/DS_FILOSOFI_SAGE_LOG_TP_NIVVIE_2023_CSV_FR
Downloaded path : C:\Users\HRTQL2\AppData\Local\Temp\DS_FILOSOFI_SAGE_LOG_TP_NIVVIE_CSV_FR.zip

'C:\\Users\\HRTQL2\\AppData\\Local\\Temp\\DS_FILOSOFI_SAGE_LOG_TP_NIVVIE_CSV_FR.zip'

Example 3 : parquet file associated with the DS "DS_RP_TD_POPULATION_AGECOUPLECIVILSEX_PRINC"

In [18]:
# Download the parquet file associated with the DS "DS_RP_TD_POPULATION_AGECOUPLECIVILSEX_PRINC" and save it as "DS_RP_TD_POPULATION_AGECOUPLECIVILSEX_PRINC.parquet"
# The parquet file corresponds to the entire database
pynsee.get_file(ds_name = "DS_RP_TD_POPULATION_AGECOUPLECIVILSEX_PRINC")

Request file : https://api.insee.fr/melodi/file/DS_RP_TD_POPULATION_AGECOUPLECIVILSEX_PRINC/PARQUET
Downloaded path : C:\Users\HRTQL2\AppData\Local\Temp\DS_RP_TD_POPULATION_AGECOUPLECIVILSEX_PRINC.parquet

'C:\\Users\\HRTQL2\\AppData\\Local\\Temp\\DS_RP_TD_POPULATION_AGECOUPLECIVILSEX_PRINC.parquet'

### V.e get_local_data function : 

#### V.e.1 Help for get_local_data :

In [19]:
# Help for the get_local_data function of the melodi submodule
help(pynsee.get_local_data)

Help on function get_local_data in module pynsee.melodi.get_local_data:

get_local_data(
    ds_name: str,
    geo: str,
    geo_object: str,
    query_filter: str = '',
    base_url_melodi: str = 'https://api.insee.fr/melodi'
) -> pd.DataFrame
    Description
    ----------

    Get data on one territory.

    Parameters
    ----------

    ds_name : dataset name - use get_ds_list to find a dataset identifier

    geo : code geo

    geo_object : geo level

    query_filter : additionnal filter on request - default : ""

    base_url_melodi : API Melodi URL - default production URL : "https://api.insee.fr/melodi"

    Returns
    -------

    DataFrame with data.

    Examples
    --------

    Example 1 :

    data=pynsee.get_local_data(

      ds_name = "DS_POPULATIONS_REFERENCE",

      geo = "69",

      geo_object = "DEP")

    data.info()
    data.head()

    Example 2 :

    data=pynsee.get_local_data(

      ds_name = "DS_POPULATIONS_REFERENCE",

      geo = "69",

      geo_object = "DEP",

      query_filter = "POPREF_MEASURE=PMUN")

    data.info()
    data.head()

#### V.e.2 Examples of using get_local_data :

Example 1 :

In [20]:
# Extract and display data for the dataset "DS_POPULATIONS_REFERENCE" selecting region 53 (REG="53", Bretagne)
data=pynsee.get_local_data(

      ds_name = "DS_POPULATIONS_REFERENCE",

      geo = "53",

      geo_object = "REG")

# Info and first 5 rows of the dataset
data.info()
data.head()

Total count request : https://api.insee.fr/melodi/data/DS_POPULATIONS_REFERENCE?GEO=REG-53&totalCount=TRUE&maxResult=0
Number of lines : 3
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GEO_REF         3 non-null      object
 1   GEO_OBJECT      3 non-null      object
 2   GEO             3 non-null      object
 3   TIME_PERIOD     3 non-null      str
 4   FREQ            3 non-null      str
 5   POPREF_MEASURE  3 non-null      str
 6   OBS_VALUE       3 non-null      float64
dtypes: float64(1), object(3), str(3)
memory usage: 327.0+ bytes

  GEO_REF GEO_OBJECT GEO TIME_PERIOD FREQ POPREF_MEASURE  OBS_VALUE
0    2025        REG  53        2023    A           PCAP    87701.0
1    2025        REG  53        2023    A           PTOT  3537071.0
2    2025        REG  53        2023    A           PMUN  3449370.0

Example 2 :

In [21]:
# Extract and display data for the dataset "DS_POPULATIONS_REFERENCE" selecting municipality code 44109 (Nantes) and the measure "PMUN"
data=pynsee.get_local_data(

      ds_name = "DS_POPULATIONS_REFERENCE",

      geo = "44109",

      geo_object = "COM",
      
      query_filter = "POPREF_MEASURE=PMUN")

# Info and first 5 rows of the dataset
data.info()
data.head()

Total count request : https://api.insee.fr/melodi/data/DS_POPULATIONS_REFERENCE?GEO=COM-44109&POPREF_MEASURE=PMUN&totalCount=TRUE&maxResult=0
Number of lines : 1
<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GEO_REF         1 non-null      object
 1   GEO_OBJECT      1 non-null      object
 2   GEO             1 non-null      object
 3   TIME_PERIOD     1 non-null      str
 4   FREQ            1 non-null      str
 5   POPREF_MEASURE  1 non-null      str
 6   OBS_VALUE       1 non-null      float64
dtypes: float64(1), object(3), str(3)
memory usage: 197.0+ bytes

  GEO_REF GEO_OBJECT    GEO TIME_PERIOD FREQ POPREF_MEASURE  OBS_VALUE
0    2025        COM  44109        2023    A           PMUN   327734.0

### V.f get_local_data_by_com function : 

#### V.f.1 Help for get_local_data_com :

In [22]:
# Help for the get_local_data_by_com function of the melodi submodule
help(pynsee.get_local_data_by_com)

Help on function get_local_data_by_com in module pynsee.melodi.get_local_data_by_com:

get_local_data_by_com(
    ds_name: str,
    geo: str,
    geo_object: str,
    query_filter: str = '',
    base_url_melodi: str = 'https://api.insee.fr/melodi'
) -> pd.DataFrame
    Description
    ----------

    Get data on every Commune of one territory.

    Parameters
    ----------

    ds_name : dataset name - use get_ds_list to find a dataset identifier

    geo : code geo

    geo_object : geo level

    query_filter : additionnal filter on request - default : ""

    base_url_melodi : API Melodi URL - default production URL : "https://api.insee.fr/melodi"

    Returns
    -------

    DataFrame with data.

    Examples
    --------

    Example 1 :

    data=pynsee.get_local_data_by_com(

      ds_name = "DS_POPULATIONS_REFERENCE",

      geo = "69",

      geo_object = "DEP")

    data.info()
    data.head()

    Example 2 :

    data=pynsee.get_local_data_by_com(

      ds_name = "DS_POPULATIONS_REFERENCE",

      geo = "69",

      geo_object = "DEP",

      query_filter = "POPREF_MEASURE=PMUN")

    data.info()
    data.head()

#### V.f.2 Examples of using get_local_data_com :

Example 1 :

In [23]:
# Extract and display data for the dataset "DS_POPULATIONS_REFERENCE" selecting municipalities in region 53 (REG="53", Bretagne)
data=pynsee.get_local_data_by_com(

      ds_name = "DS_POPULATIONS_REFERENCE",

      geo = "53",

      geo_object = "REG")

# Info and first 5 rows of the dataset
data.info()
data.head()

Total count request : https://api.insee.fr/melodi/data/DS_POPULATIONS_REFERENCE?GEO=REG-53*COM&totalCount=TRUE&maxResult=0
Number of lines : 3,606
<class 'pandas.DataFrame'>
RangeIndex: 3606 entries, 0 to 3605
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GEO_REF         3606 non-null   object
 1   GEO_OBJECT      3606 non-null   object
 2   GEO             3606 non-null   object
 3   TIME_PERIOD     3606 non-null   str
 4   FREQ            3606 non-null   str
 5   POPREF_MEASURE  3606 non-null   str
 6   OBS_VALUE       3606 non-null   float64
dtypes: float64(1), object(3), str(3)
memory usage: 229.0+ KB

  GEO_REF GEO_OBJECT    GEO TIME_PERIOD FREQ POPREF_MEASURE  OBS_VALUE
0    2025        COM  22077        2023    A           PMUN     1294.0
1    2025        COM  22079        2023    A           PCAP       41.0
2    2025        COM  22055        2023    A           PCAP      213.0
3    2025        COM  22030        2023    A           PCAP       19.0
4    2025        COM  22047        2023    A           PMUN      914.0

Example 2 :

In [24]:
# Extract and display data for the dataset "DS_POPULATIONS_REFERENCE" selecting municipalities in department 44 (DEP="44", Loire-Atlantique) and indicator "PMUN" (municipal population)

data=pynsee.get_local_data_by_com(

      ds_name = "DS_POPULATIONS_REFERENCE",

      geo = "44",

      geo_object = "DEP",
      
      query_filter = "POPREF_MEASURE=PMUN")

# Info and first 5 rows of the dataset
data.info()
data.head()

Total count request : https://api.insee.fr/melodi/data/DS_POPULATIONS_REFERENCE?GEO=DEP-44*COM&POPREF_MEASURE=PMUN&totalCount=TRUE&maxResult=0
Number of lines : 207
<class 'pandas.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   GEO_REF         207 non-null    object
 1   GEO_OBJECT      207 non-null    object
 2   GEO             207 non-null    object
 3   TIME_PERIOD     207 non-null    str
 4   FREQ            207 non-null    str
 5   POPREF_MEASURE  207 non-null    str
 6   OBS_VALUE       207 non-null    float64
dtypes: float64(1), object(3), str(3)
memory usage: 13.3+ KB

  GEO_REF GEO_OBJECT    GEO TIME_PERIOD FREQ POPREF_MEASURE  OBS_VALUE
0    2025        COM  44043        2023    A           PMUN     7452.0
1    2025        COM  44136        2023    A           PMUN     1321.0
2    2025        COM  44179        2023    A           PMUN     5523.0
3    2025        COM  44124        2023    A           PMUN      868.0
4    2025        COM  44129        2023    A           PMUN    11474.0

### V.g get_metadata function : 

#### V.g.1 Help for get_metadata :

In [25]:
# Help for the get_metadata function of the melodi submodule
help(pynsee.get_metadata)

Help on function get_metadata in module pynsee.melodi.get_metadata:

get_metadata(ds_name: str, base_url_melodi: str = 'https://api.insee.fr/melodi')
    Description
    ----------

    Get dataset metadata.

    Parameters
    ----------

    ds_name : dataset name

    base_url_melodi : API Melodi URL - default production URL : "https://api.insee.fr/melodi"

    Returns
    -------

    List dataset metadata.

    Examples
    --------

    metadata=pynsee.get_metadata(ds_name = "DS_POPULATIONS_REFERENCE")

#### V.g.2 Examples of using get_metadata :

Example 1 :

In [26]:
# Extract and display metadata for the dataset "DS_POPULATIONS_REFERENCE"
metadata=pynsee.get_metadata(ds_name = "DS_POPULATIONS_REFERENCE")

Request dataset: https://api.insee.fr/melodi/catalog/DS_POPULATIONS_REFERENCE

 abstract :
 [{'content': 'Données de populations de référence : population municipale, population comptée à part et population totale pour les différentes circonscriptions administratives : régions, départements, arrondissements et communes. ', 'lang': 'fr'}, {'content': 'The population data as of January 1, 2022, within the territorial boundaries of the municipalities as of January 1, 2024, is official and authenticated by decree. This data will take effect on January 1, 2025. The population figures are available for the various administrative divisions as of January 1, 2024, based on their territorial boundaries on that date: regions, departments, districts, and municipalities', 'lang': 'en'}]

 accessRights :
 [{'content': 'Public', 'lang': 'fr'}, {'content': 'Public', 'lang': 'en'}]

 accrualPeriodicity :
 {'label': [{'content': 'Annuel', 'lang': 'fr'}, {'content': 'Annual', 'lang': 'en'}]}

 confidentialityStatus :
 [{'content': 'Libre', 'lang': 'fr'}, {'content': 'Free', 'lang': 'en'}]

 creator :
 Insee

 description :
 [{'content': "La loi du 27 février 2002 relative à la démocratie de proximité fixe comme premier objectif du recensement de la population la publication tous les ans des chiffres des populations de référence (ou populations légales) : population municipale, population comptée à part et population totale. Ces chiffres sont calculés pour la France, toutes ses communes et circonscriptions administratives. La responsabilité du calcul des populations de référence est confiée à l'Insee. \n\nLes données de population au 1er janvier 2023 dans les limites territoriales des communes au 1er janvier 2025 sont officielles et authentifiées par décret. Elles entrent en vigueur au\xa01er\xa0janvier\xa02026. ", 'lang': 'fr'}, {'content': 'The law of February 27, 2002, concerning local democracy, establishes as the primary objective of the population census the annual publication of legal population figures: municipal population, population counted separately, and total population. These figures are calculated for France, all its municipalities, and administrative districts. The responsibility for calculating legal populations is entrusted to INSEE.', 'lang': 'en'}]

 identifier :
 DS_POPULATIONS_REFERENCE

 issued :
 2025-12-17T08:35:21.000297779

 keyword :
 [{'label': [{'content': 'population', 'lang': 'fr'}, {'content': 'population', 'lang': 'en'}]}, {'label': [{'content': 'population municipale ', 'lang': 'fr'}, {'content': 'municipal population', 'lang': 'en'}]}, {'label': [{'content': 'population comptée à part', 'lang': 'fr'}, {'content': 'population counted apart', 'lang': 'en'}]}, {'label': [{'content': 'population totale', 'lang': 'fr'}, {'content': 'total population', 'lang': 'en'}]}, {'label': [{'content': 'populations légales', 'lang': 'fr'}, {'content': 'legal populations', 'lang': 'en'}]}, {'label': [{'content': 'population de référence', 'lang': 'fr'}, {'content': 'reference population', 'lang': 'en'}]}]

 landingPage :
 [[{'lang': 'fr', 'url': ''}, {'lang': 'en', 'url': ''}]]

 modified :
 2025-12-18T12:00:16.299984912

 numObservations :
 106065

 numSeries :
 0

 processStep :
 [{'content': 'inseeApi', 'lang': 'fr'}, {'content': 'inseeApi', 'lang': 'en'}]

 product :
 [{'accessURL': 'https://api.insee.fr/melodi/file/DS_POPULATIONS_REFERENCE/DS_POPULATIONS_REFERENCE_2023_CSV_FR', 'byteSize': 985016, 'format': 'CSV', 'id': 'DS_POPULATIONS_REFERENCE_2023_CSV_FR', 'issued': '2025-12-17T08:50:56', 'language': 'FR', 'mediaType': 'text/csv', 'modified': '2026-02-17T12:08:49.311695357', 'packageFormat': 'application/zip', 'title': 'Populations de référence'}]

 publisher :
 {'id': 'INSEE', 'label': [{'content': 'Institut national de la statistique et des etudes economiques (INSEE)', 'lang': 'fr'}, {'content': 'National Institute of Statistics and Economic Studies', 'lang': 'en'}]}

 relations :
 [{'title': [{'content': '', 'lang': 'fr'}, {'content': '', 'lang': 'en'}], 'titleComplement': [{'content': 'Documentation et données complémentaires', 'lang': 'fr'}, {'lang': 'en'}], 'url': [{'content': 'https://www.insee.fr/fr/statistiques/8681011', 'lang': 'fr'}, {'lang': 'en'}]}, {'title': [{'content': '', 'lang': 'fr'}, {'content': '', 'lang': 'en'}], 'titleComplement': [{'content': '', 'lang': 'fr'}, {'lang': 'en'}], 'url': [{'content': '', 'lang': 'fr'}, {'lang': 'en'}]}]

 scopeNote :
 [{'content': '', 'lang': 'fr'}, {'content': 'The term “reference populations” replaces the former term “legal populations” used until 2021. This change is based on a recommendation from the official statistics authority. ', 'lang': 'en'}]

 spatial :
 {'id': 'FEHM', 'label': [{'content': 'France hors Mayotte', 'lang': 'fr'}, {'content': 'France excluding Mayotte', 'lang': 'en'}]}

 spatialResolution :
 [{'id': 'COM', 'label': [{'content': 'Commune', 'lang': 'fr'}, {'content': 'Commune', 'lang': 'en'}]}, {'id': 'ARM', 'label': [{'content': 'Arrondissement municipal', 'lang': 'fr'}, {'content': 'Municipal district', 'lang': 'en'}]}, {'id': 'ARR', 'label': [{'content': 'Arrondissement', 'lang': 'fr'}, {'content': 'District', 'lang': 'en'}]}, {'id': 'DEP', 'label': [{'content': 'Département', 'lang': 'fr'}, {'content': 'Department', 'lang': 'en'}]}, {'id': 'REG', 'label': [{'content': 'Région', 'lang': 'fr'}, {'content': 'Region', 'lang': 'en'}]}, {'id': 'FRANCE', 'label': [{'content': 'France', 'lang': 'fr'}, {'content': 'France', 'lang': 'en'}]}]

 spatialTemporal :
 2025-01-01T01:00:00

 statisticalUnit :
 [{'label': [{'content': 'Individu', 'lang': 'fr'}, {'content': 'Person', 'lang': 'en'}]}]

 status :
 {'id': 'publie', 'label': [{'content': 'Publié', 'lang': 'fr'}, {'content': 'Completed', 'lang': 'en'}]}

 structure :
 {'dsd': 'DSD_POPULATIONS_REFERENCE'}

 subtitle :
 [{'content': 'Recensement de la population', 'lang': 'fr'}, {'content': '', 'lang': 'en'}]

 temporal :
 {'endPeriod': '2023-01-01T00:00:00', 'startPeriod': '2023-01-01T00:00:00'}

 temporalResolution :
 [{'label': [{'content': 'Annuel', 'lang': 'fr'}, {'content': 'Annual', 'lang': 'en'}]}]

 theme :
 [{'label': [{'content': '1.1 Population et immigration', 'lang': 'fr'}, {'content': '1.1 Population and migration', 'lang': 'en'}], 'themeTaxonomy': 'classificationOfStatisticalDomain'}, {'label': [{'content': '1. Statistiques démographiques et sociales', 'lang': 'fr'}, {'content': '1. Demographic and social statistics', 'lang': 'en'}], 'themeTaxonomy': 'classificationOfStatisticalDomain'}, {'label': [{'content': 'Démographie', 'lang': 'fr'}, {'content': 'Demography', 'lang': 'en'}], 'themeTaxonomy': 'inseeTheme'}]

 title :
 [{'content': 'Populations de référence', 'lang': 'fr'}, {'content': 'Reference populations ', 'lang': 'en'}]

 type :
 [{'content': 'Datacube', 'lang': 'fr'}, {'content': 'Datacube', 'lang': 'en'}]

 uri :
 http://id.insee.fr/catalogues/jeuDeDonnees/c322eb4d-ec91-4723-8804-ea62e492612b

 uuid :
 3f4f0ee8-0ddd-173f-3565-a1110e66c088

 wasGeneratedBy :
 [{'id': 's1321', 'label': [{'content': 'Recensement de la population', 'lang': 'fr'}, {'content': 'Population census', 'lang': 'en'}]}, {'id': 's21', 'label': [{'content': 'Recensement de la population', 'lang': 'fr'}, {'content': 'Population census', 'lang': 'en'}]}]

Example 2 :

In [27]:
# Extract and display metadata for the dataset "DS_SRCV_PMS"
metadata=pynsee.get_metadata(ds_name = "DS_SRCV_PMS")

Request dataset: https://api.insee.fr/melodi/catalog/DS_SRCV_PMS

 abstract :
 [{'content': 'Données regroupant des indicateurs annuels sur la privation matérielle et sociale pour la France hors Mayotte.', 'lang': 'fr'}, {'content': 'Annual indicators on material and social deprivation in France (excluding Mayotte).', 'lang': 'en'}]

 accessRights :
 [{'content': 'Public', 'lang': 'fr'}, {'content': 'Free', 'lang': 'en'}]

 accessURLParquet :
 https://api.insee.fr/melodi/file/DS_SRCV_PMS_2025/PARQUET

 accrualPeriodicity :
 {'label': [{'content': 'Annuel', 'lang': 'fr'}, {'content': 'Annual', 'lang': 'en'}]}

 confidentialityStatus :
 [{'content': 'Libre', 'lang': 'fr'}, {'content': 'Free', 'lang': 'en'}]

 creator :
 Insee

 description :
 [{'content': "Données annuelles sur la privation matérielle et sociale. L'indicateur européen de privation matérielle et sociale mesure la part de la population se trouvant dans l’incapacité de couvrir les dépenses liées à au moins cinq éléments de la vie courante sur les 13 considérés comme souhaitables, voire nécessaires, pour avoir un niveau de vie acceptable. Il est décliné selon l'âge, le sexe, le niveau de vie du ménage, la composition de la famille, le diplôme, la catégorie socioprofessionnelle, la situation vis-à-vis de l'emploi, le statut d'occupation du logement, l'indicateur de limitation d'activité générale et la note donnée à l'état de santé en général.\nLes données annuelles sur la privation matérielle et sociale sont incluses dans les jeux de données à forte valeur désignées par Eurostat (HVD).", 'lang': 'fr'}, {'content': 'Annual data on material and social deprivation.The European material and social deprivation indicator measures the proportion of the population unable to afford at least five items out of a list of 13 considered desirable, or even necessary, to maintain an acceptable standard of living. It is broken down by age, sex, household income, family composition, level of education, socio-professional category, employment status, housing tenure status, global activity limitation indicator, and self-rated general health.\nThe annual data on material and social deprivation are included in the high-value datasets designated by Eurostat (HVD).', 'lang': 'en'}]

 identifier :
 DS_SRCV_PMS

 issued :
 2026-09-28T17:01:12.000724204

 keyword :
 [{'label': [{'content': 'HVD', 'lang': 'fr'}, {'content': 'HVD', 'lang': 'en'}]}]

 landingPage :
 [[{'lang': 'fr', 'url': ''}, {'lang': 'en', 'url': ''}]]

 modified :
 2026-09-29T14:00:38.299099813

 numObservations :
 9240

 numSeries :
 0

 ordreComposants :
 ['TIME_PERIOD', 'GEO', 'SEX', 'AGE', 'PCS', 'EDUC', 'EMPSTA_ENQ', 'TPH', 'TSH', 'HLTH_SPH', 'HLTH_GALI', 'QUANTILE_NIVVIE', 'SRCV_MEASURE', 'OBS_VALUE', 'OBS_STATUS', 'CONF_STATUS', 'FREQ']

 processStep :
 [{'content': 'inseeApi', 'lang': 'fr'}, {'content': 'inseeApi', 'lang': 'en'}]

 product :
 [{'accessURL': 'https://api.insee.fr/melodi/file/DS_SRCV_PMS/DS_SRCV_PMS_2025_CSV_FR', 'byteSize': 57905, 'format': 'CSV', 'id': 'DS_SRCV_PMS_2025_CSV_FR', 'issued': '2026-09-29T09:17:58.771334089', 'language': 'FR', 'mediaType': 'text/csv', 'modified': '2026-09-29T09:17:58.771334089', 'packageFormat': 'application/zip', 'title': 'Privations matérielles et sociales'}]

 publisher :
 {'id': 'INSEE', 'label': [{'content': 'Institut national de la statistique et des etudes economiques (INSEE)', 'lang': 'fr'}, {'content': 'National Institute of Statistics and Economic Studies', 'lang': 'en'}]}

 relations :
 [{'title': [{'content': 'Insee Résultats', 'lang': 'fr'}, {'content': 'Insee Results', 'lang': 'en'}], 'titleComplement': [{'content': '"Privations matérielles et sociales de 2020 à 2025"', 'lang': 'fr'}, {'lang': 'en'}], 'url': [{'content': 'https://www.insee.fr/fr/statistiques/9051733', 'lang': 'fr'}, {'lang': 'en'}]}, {'title': [{'content': 'Documentation', 'lang': 'fr'}, {'content': 'Documentation', 'lang': 'en'}], 'titleComplement': [{'content': '"Statistiques sur les ressources et conditions de vie (SRCV)"', 'lang': 'fr'}, {'lang': 'en'}], 'url': [{'content': 'https://www.insee.fr/fr/metadonnees/source/serie/s1220', 'lang': 'fr'}, {'lang': 'en'}]}]

 scopeNote :
 [{'content': "Depuis 2022, le champ géographique de l’enquête a été élargi aux départements d’outre-mer hors Mayotte.\n\nPour le statut d'occupation du logement, la modalité total comprend les personnes logées à titre gratuit.", 'lang': 'fr'}, {'content': 'As of 2022, the survey’s geographical coverage has been expanded to include the overseas departments, except Mayotte.\n\nFor housing tenure status, the total category includes rent-free tenants.', 'lang': 'en'}]

 spatial :
 {'id': 'FEHM', 'label': [{'content': 'France hors Mayotte', 'lang': 'fr'}, {'content': 'France excluding Mayotte', 'lang': 'en'}]}

 spatialResolution :
 [{'id': 'FRANCE', 'label': [{'content': 'France', 'lang': 'fr'}, {'content': 'France', 'lang': 'en'}]}]

 spatialTemporal :
 2026-01-01T01:00:00

 statisticalUnit :
 [{'label': [{'content': 'Individu', 'lang': 'fr'}, {'content': 'Person', 'lang': 'en'}]}]

 status :
 {'id': 'publie', 'label': [{'content': 'Publié', 'lang': 'fr'}, {'content': 'Completed', 'lang': 'en'}]}

 structure :
 {'dsd': 'DSD_SRCV_PMS_2025'}

 subtitle :
 [{'content': 'Enquête statistiques sur les ressources et les conditions de vie (SRCV)', 'lang': 'fr'}, {'content': 'Statistics on Income and Living Conditions survey (SILC)', 'lang': 'en'}]

 tailleFichierParquetEnOctets :
 22353

 temporal :
 {'endPeriod': '2025-01-01T00:00:00', 'startPeriod': '2020-01-01T00:00:00'}

 temporalResolution :
 [{'label': [{'content': 'Annuel', 'lang': 'fr'}, {'content': 'Annual', 'lang': 'en'}]}]

 theme :
 [{'label': [{'content': '3.3.1 Conditions de vie et pauvreté ', 'lang': 'fr'}, {'content': '3.3.1 Living conditions, poverty and cross-cutting social issues', 'lang': 'en'}], 'themeTaxonomy': 'classificationOfStatisticalDomain'}, {'label': [{'content': '3.3 Statistiques et indicateurs multi-domaines', 'lang': 'fr'}, {'content': '3.3 Multi-domain statistics and indicators', 'lang': 'en'}], 'themeTaxonomy': 'classificationOfStatisticalDomain'}, {'label': [{'content': '3. Environnement et statistiques multi-domaines', 'lang': 'fr'}, {'content': '3 Environment and multi-domain statistics', 'lang': 'en'}], 'themeTaxonomy': 'classificationOfStatisticalDomain'}, {'label': [{'content': 'Pauvreté – Précarité', 'lang': 'fr'}, {'content': 'Poverty –\xa0precarity', 'lang': 'en'}], 'themeTaxonomy': 'inseeTheme'}, {'label': [{'content': "Revenus – Pouvoir d'achat – Consommation", 'lang': 'fr'}, {'content': 'Income – Purchasing power – Consumption', 'lang': 'en'}], 'themeTaxonomy': 'inseeTheme'}]

 title :
 [{'content': 'Privations matérielles et sociales', 'lang': 'fr'}, {'content': 'Material and social deprivations', 'lang': 'en'}]

 type :
 [{'content': 'Générique', 'lang': 'fr'}, {'content': 'Generic', 'lang': 'en'}]

 uri :
 http://id.insee.fr/catalogues/jeuDeDonnees/a4a7f9b9-a5c0-4345-9dda-7ebe9d87440a

 uuid :
 0a17ebcc-06cb-41a7-a910-eb69dd009d24

 wasGeneratedBy :
 [{'id': 's1220', 'label': [{'content': 'Statistiques sur les ressources et conditions de vie', 'lang': 'fr'}, {'content': 'Statistics on income and living conditions', 'lang': 'en'}]}, {'id': 's11', 'label': [{'content': 'Ressources et conditions de vie', 'lang': 'fr'}, {'content': 'Resources and living conditions', 'lang': 'en'}]}]

### V.h get_range function : 

#### V.h.1 Help for get_range :

In [28]:
# Help for the get_range function of the melodi submodule
help(pynsee.get_range)

Help on function get_range in module pynsee.melodi.get_range:

get_range(
    ds_name: str,
    base_url_melodi: str = 'https://api.insee.fr/melodi',
    lang: str = 'fr',
    exclusions_list: list = ['GEO']
) -> pd.DataFrame
    Description
    ----------
    Get dataset range (codes and labels).
    Retrieves the list of dimensions and all their possible modalities values (codes and human-readable labels) for a given dataset.
    For GEO dimension, it is recommanded to used dedicated function : get_range_geo().

    Parameters
    ----------

    ds_name : dataset name

    base_url_melodi : API Melodi URL - default prod

    lang : french (fr) or english (en) labels - default french ("fr")

    exclusions_list : exclude some dimensions for a faster and light result - default : "GEO"

    Returns
    -------

    DataFrame with dimensions and modalities codes and labels

    Examples
    --------

    Example 1 :

    data=pynsee.get_range("DS_POPULATIONS_REFERENCE")

    data.info()
    data.head()

    Example 2 :

    data=pynsee.get_range(ds_name = "DS_EC_DECES",lang="en")

    data.info()
    data.head()

#### V.h.2 Examples of using get_range :

Example 1 :

In [29]:
# Extract and display variables/modalities for the dataset "DS_FILOSOFI_CC"
data=pynsee.get_range("DS_FILOSOFI_CC")

data.info()
data.head()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DIM        37 non-null     str
 1   DIM_LABEL  37 non-null     str
 2   MOD        37 non-null     str
 3   MOD_LABEL  37 non-null     str
dtypes: str(4)
memory usage: 4.2 KB

,DIM,DIM_LABEL,MOD,MOD_LABEL
0,CONF_STATUS,Statut de confidentialité,C,Confidentiel (secret statistique)
1,CONF_STATUS,Statut de confidentialité,F,Diffusable
2,FILOSOFI_MEASURE,Mesures filosofi,D1_SL,1er décile du niveau de vie (en euros)
3,FILOSOFI_MEASURE,Mesures filosofi,D2_SL,2e décile du niveau de vie (en euros)
4,FILOSOFI_MEASURE,Mesures filosofi,D3_SL,3e décile du niveau de vie (en euros)

Example 2 :

In [30]:
# Extract and display variables/modalities for the dataset "DS_FILOSOFI_CC" in English
data=pynsee.get_range("DS_FILOSOFI_CC",lang="en")

data.info()
data.head()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   DIM        37 non-null     str
 1   DIM_LABEL  37 non-null     str
 2   MOD        37 non-null     str
 3   MOD_LABEL  37 non-null     str
dtypes: str(4)
memory usage: 4.3 KB

,DIM,DIM_LABEL,MOD,MOD_LABEL
0,CONF_STATUS,Confidentiality status,C,Confidential statistical information
1,CONF_STATUS,Confidentiality status,F,Free for publication
2,FILOSOFI_MEASURE,Measures filosofi,D1_SL,1st decile of the standard of living (in euros)
3,FILOSOFI_MEASURE,Measures filosofi,D2_SL,2nd decile of the standard of living (in euros)
4,FILOSOFI_MEASURE,Measures filosofi,D3_SL,3rd decile of the standard of living (in euros)

### V.i get_range_geo function : 

#### V.i.1 Help for get_range_geo :

In [31]:
# Help for the get_range_geo function of the melodi submodule
help(pynsee.get_range_geo)

Help on function get_range_geo in module pynsee.melodi.get_range_geo:

get_range_geo(
    ds_name: str,
    base_url_melodi: str = 'https://api.insee.fr/melodi',
    lang: str = 'fr'
) -> pd.DataFrame
    Description
    ----------

    Get dataset's geography : codes and labels.
    Retrieves the list of geo dimensions and all their possible values (codes and human-readable labels) for a given dataset.

    Parameters
    ----------

    ds_name : dataset name

    base_url_melodi : API Melodi URL - default prod

    lang : french (fr) or english (en) labels - default french ("fr")

    Returns
    -------

    DataFrame with columns `GEO_REF`, `GEO_OBJECT`, `GEO_OBJECT_LABEL`, `GEO`, `GEO_LABEL`

    Examples
    --------

    Example 1 :

    data=pynsee.get_range_geo("DS_POPULATIONS_REFERENCE",lang="en")

    data.info()
    data.head()

    Example 2 :

    data=pynsee.get_range_geo("DS_TICM_PRATIQUES")

    data.info()
    data.head()

#### V.i.2 Examples of using get_range_geo :

Example 1 :

In [32]:
# Extract and display geographic zones for the dataset "DS_RP_MENAGES_PRINC_IRIS"
data=pynsee.get_range_geo("DS_RP_MENAGES_PRINC_IRIS")

data.info()
data.head()

<class 'pandas.DataFrame'>
RangeIndex: 49219 entries, 0 to 49218
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GEO_REF           49219 non-null  object
 1   GEO_OBJECT        49219 non-null  str
 2   GEO_OBJECT_LABEL  49219 non-null  str
 3   GEO               49219 non-null  str
 4   GEO_LABEL         49219 non-null  str
dtypes: object(1), str(4)
memory usage: 3.2+ MB

  GEO_REF GEO_OBJECT GEO_OBJECT_LABEL    GEO                GEO_LABEL
0    2025        COM          Commune  01001  L'Abergement-Clémenciat
1    2025        COM          Commune  01002    L'Abergement-de-Varey
2    2025        COM          Commune  01005      Ambérieux-en-Dombes
3    2025        COM          Commune  01006                  Ambléon
4    2025        COM          Commune  01007                 Ambronay

Example 2 :

In [33]:
# Extract and display geographic zones for the dataset "DS_RP_MENAGES_PRINC_IRIS" in English
data=pynsee.get_range_geo("DS_RP_MENAGES_PRINC_IRIS",lang="en")

data.info()
data.head()

<class 'pandas.DataFrame'>
RangeIndex: 49219 entries, 0 to 49218
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   GEO_REF           49219 non-null  object
 1   GEO_OBJECT        49219 non-null  str
 2   GEO_OBJECT_LABEL  49219 non-null  str
 3   GEO               49219 non-null  str
 4   GEO_LABEL         49219 non-null  str
dtypes: object(1), str(4)
memory usage: 3.2+ MB

  GEO_REF GEO_OBJECT GEO_OBJECT_LABEL    GEO                GEO_LABEL
0    2025        COM          Commune  01001  L'Abergement-Clémenciat
1    2025        COM          Commune  01002    L'Abergement-de-Varey
2    2025        COM          Commune  01005      Ambérieux-en-Dombes
3    2025        COM          Commune  01006                  Ambléon
4    2025        COM          Commune  01007                 Ambronay

## VI. Using the polars module, which is similar to dplyr

In [34]:
# Import the polars module installed via the command "pip install polars" in the VS Code terminal
# pl is an alias for the polars module, which is a data manipulation library in Python. It provides data structures and functions to work with data frames, similar to pandas, but with improved performance for large datasets.
import polars as pl

### VI.a Import a dataset

In [35]:
# Extract the dataset "DS_RP_MENAGES_PRINC_IRIS" selecting the measure "POP" or "ONEPERS", civil status "_T", and age "Y_GE15" using the get_data function of the melodi submodule
POP_IRIS=pynsee.get_data("https://api.insee.fr/melodi/data/DS_RP_MENAGES_PRINC_IRIS?RP_MEASURE=POP&RP_MEASURE=ONEPERS&CIVIL_STATUS=_T&AGE=Y_GE15")

Total count request : https://api.insee.fr/melodi/data/DS_RP_MENAGES_PRINC_IRIS?RP_MEASURE=POP&RP_MEASURE=ONEPERS&CIVIL_STATUS=_T&AGE=Y_GE15&totalCount=TRUE&maxResult=0
Number of lines : 98,438

### VI.b Filter data

In [36]:
# Convert the pandas dataframe into a polars dataframe, mandatory to use polars methods/functions
POP_IRIS=pl.from_pandas(POP_IRIS)

# Filter the POP_IRIS table to keep only the total population (RP_MEASURE=POP)
POP_IRIS=POP_IRIS.filter(pl.col("RP_MEASURE")=="POP")

# Some polars dataframe methods

## First and last 5 rows of the POP_IRIS dataframe
POP_IRIS.head(5)
POP_IRIS.tail(5)

## Number of rows and columns of the POP_IRIS dataframe
POP_IRIS.shape

## Display the type of each column of the POP_IRIS dataframe
POP_IRIS.schema

## Statistical description of the columns of the POP_IRIS dataframe
POP_IRIS.describe()

shape: (9, 17)
┌────────────┬─────────┬────────────┬───────────┬───┬──────────┬────────┬────────────┬─────────────┐
│ statistic  ┆ GEO_REF ┆ GEO_OBJECT ┆ GEO       ┆ … ┆ LAB_IRIS ┆ AGE    ┆ OBS_STATUS ┆ OBS_VALUE   │
│ ---        ┆ ---     ┆ ---        ┆ ---       ┆   ┆ ---      ┆ ---    ┆ ---        ┆ ---         │
│ str        ┆ str     ┆ str        ┆ str       ┆   ┆ str      ┆ str    ┆ str        ┆ f64         │
╞════════════╪═════════╪════════════╪═══════════╪═══╪══════════╪════════╪════════════╪═════════════╡
│ count      ┆ 49219   ┆ 49219      ┆ 49219     ┆ … ┆ 49219    ┆ 49219  ┆ 49219      ┆ 49219.0     │
│ null_count ┆ 0       ┆ 0          ┆ 0         ┆ … ┆ 0        ┆ 0      ┆ 0          ┆ 0.0         │
│ mean       ┆ null    ┆ null       ┆ null      ┆ … ┆ null     ┆ null   ┆ null       ┆ 1147.634324 │
│ std        ┆ null    ┆ null       ┆ null      ┆ … ┆ null     ┆ null   ┆ null       ┆ 1124.799552 │
│ min        ┆ 2025    ┆ COM        ┆ 01001     ┆ … ┆ 1        ┆ Y_GE15 ┆ A          ┆ 0.0         │
│ 25%        ┆ null    ┆ null       ┆ null      ┆ … ┆ null     ┆ null   ┆ null       ┆ 220.0       │
│ 50%        ┆ null    ┆ null       ┆ null      ┆ … ┆ null     ┆ null   ┆ null       ┆ 705.9942    │
│ 75%        ┆ null    ┆ null       ┆ null      ┆ … ┆ null     ┆ null   ┆ null       ┆ 1880.14472  │
│ max        ┆ 2025    ┆ IRIS       ┆ 974240105 ┆ … ┆ Z        ┆ Y_GE15 ┆ A          ┆ 11415.83741 │
└────────────┴─────────┴────────────┴───────────┴───┴──────────┴────────┴────────────┴─────────────┘

### VI.c Select columns and rename a variable

In [37]:
# Select the columns "TIME_PERIOD", "GEO_OBJECT", "GEO", "LAB_IRIS", and "OBS_VALUE" from the POP_IRIS dataframe and rename "OBS_VALUE" to "POP_IRIS"
POP_IRIS=POP_IRIS.select("TIME_PERIOD","GEO_OBJECT","GEO","LAB_IRIS","OBS_VALUE").rename({"OBS_VALUE":"POP_IRIS"})  

# First 5 rows of the POP_IRIS dataframe
POP_IRIS.head(5)

shape: (5, 5)
┌─────────────┬────────────┬───────┬──────────┬────────────┐
│ TIME_PERIOD ┆ GEO_OBJECT ┆ GEO   ┆ LAB_IRIS ┆ POP_IRIS   │
│ ---         ┆ ---        ┆ ---   ┆ ---      ┆ ---        │
│ str         ┆ str        ┆ str   ┆ str      ┆ f64        │
╞═════════════╪════════════╪═══════╪══════════╪════════════╡
│ 2023        ┆ COM        ┆ 01001 ┆ 5        ┆ 699.19487  │
│ 2023        ┆ COM        ┆ 01002 ┆ 5        ┆ 214.19188  │
│ 2023        ┆ COM        ┆ 01005 ┆ 5        ┆ 1553.97385 │
│ 2023        ┆ COM        ┆ 01006 ┆ 5        ┆ 104.91228  │
│ 2023        ┆ COM        ┆ 01007 ┆ 5        ┆ 2269.07667 │
└─────────────┴────────────┴───────┴──────────┴────────────┘

### VI.d Merge tables

In [38]:
# Import data to get the number of people with a Bac+5 or higher degree per IRIS
DIPLO_BAC_PLUS_5_OU_PLUS=pynsee.get_data("https://api.insee.fr/melodi/data/DS_RP_DIPLOMES_PRINC_IRIS?SEX=_T&EDUC=700_RP")

# Transform the pandas dataframe into a polars dataframe to use polars methods/functions
DIPLO_BAC_PLUS_5_OU_PLUS=pl.from_pandas(DIPLO_BAC_PLUS_5_OU_PLUS)

# Select only the relevant columns in the DIPLO_BAC_PLUS_5_OU_PLUS dataframe
DIPLO_BAC_PLUS_5_OU_PLUS=DIPLO_BAC_PLUS_5_OU_PLUS.select("TIME_PERIOD","GEO_OBJECT","GEO","LAB_IRIS","OBS_VALUE").rename({"OBS_VALUE":"POP_DIPLO_BAC_PLUS_5_OU_PLUS"})

# Merge the two dataframes POP_IRIS and DIPLO_BAC_PLUS_5_OU_PLUS on TIME_PERIOD, GEO_OBJECT, GEO, and LAB_IRIS columns
POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS=POP_IRIS.join(DIPLO_BAC_PLUS_5_OU_PLUS, on=["TIME_PERIOD","GEO_OBJECT","GEO","LAB_IRIS"], how="inner")

# First 5 rows of the POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS dataframe
POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS.head(5)

Total count request : https://api.insee.fr/melodi/data/DS_RP_DIPLOMES_PRINC_IRIS?SEX=_T&EDUC=700_RP&totalCount=TRUE&maxResult=0
Number of lines : 49,219

shape: (5, 6)
┌─────────────┬────────────┬───────┬──────────┬────────────┬──────────────────────────────┐
│ TIME_PERIOD ┆ GEO_OBJECT ┆ GEO   ┆ LAB_IRIS ┆ POP_IRIS   ┆ POP_DIPLO_BAC_PLUS_5_OU_PLUS │
│ ---         ┆ ---        ┆ ---   ┆ ---      ┆ ---        ┆ ---                          │
│ str         ┆ str        ┆ str   ┆ str      ┆ f64        ┆ f64                          │
╞═════════════╪════════════╪═══════╪══════════╪════════════╪══════════════════════════════╡
│ 2023        ┆ COM        ┆ 01001 ┆ 5        ┆ 699.19487  ┆ 40.94852                     │
│ 2023        ┆ COM        ┆ 01002 ┆ 5        ┆ 214.19188  ┆ 25.92132                     │
│ 2023        ┆ COM        ┆ 01005 ┆ 5        ┆ 1553.97385 ┆ 93.79963                     │
│ 2023        ┆ COM        ┆ 01006 ┆ 5        ┆ 104.91228  ┆ 6.05263                      │
│ 2023        ┆ COM        ┆ 01007 ┆ 5        ┆ 2269.07667 ┆ 201.56455                    │
└─────────────┴────────────┴───────┴──────────┴────────────┴──────────────────────────────┘

### VI.e Create/modify a column

In [39]:
# Calculate the percentage of people with a Bac+5 or higher degree per IRIS and round the result to 2 decimal places
POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS = (
    POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS
    .filter(pl.col("POP_IRIS") != 0) # Filter out rows where total population (POP_IRIS) is zero to prevent division by zero
    .with_columns(
        (
            pl.col("POP_DIPLO_BAC_PLUS_5_OU_PLUS")
            / pl.col("POP_IRIS")
            * 100 # Calculate the percentage of people with a Bac+5 or higher degree per IRIS
        )
        .round(2) # Round the result to 2 decimal places
        .alias("POURCENTAGE_DIPLO_BAC_PLUS_5_OU_PLUS") # Name the new column "POURCENTAGE_DIPLO_BAC_PLUS_5_OU_PLUS"
    )
)

# First 5 rows of the POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS dataframe
POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS.head(5)

shape: (5, 7)
┌─────────────┬────────────┬───────┬──────────┬────────────┬───────────────────┬───────────────────┐
│ TIME_PERIOD ┆ GEO_OBJECT ┆ GEO   ┆ LAB_IRIS ┆ POP_IRIS   ┆ POP_DIPLO_BAC_PLU ┆ POURCENTAGE_DIPLO │
│ ---         ┆ ---        ┆ ---   ┆ ---      ┆ ---        ┆ S_5_OU_PLUS       ┆ _BAC_PLUS_5_O…    │
│ str         ┆ str        ┆ str   ┆ str      ┆ f64        ┆ ---               ┆ ---               │
│             ┆            ┆       ┆          ┆            ┆ f64               ┆ f64               │
╞═════════════╪════════════╪═══════╪══════════╪════════════╪═══════════════════╪═══════════════════╡
│ 2023        ┆ COM        ┆ 01001 ┆ 5        ┆ 699.19487  ┆ 40.94852          ┆ 5.86              │
│ 2023        ┆ COM        ┆ 01002 ┆ 5        ┆ 214.19188  ┆ 25.92132          ┆ 12.1              │
│ 2023        ┆ COM        ┆ 01005 ┆ 5        ┆ 1553.97385 ┆ 93.79963          ┆ 6.04              │
│ 2023        ┆ COM        ┆ 01006 ┆ 5        ┆ 104.91228  ┆ 6.05263           ┆ 5.77              │
│ 2023        ┆ COM        ┆ 01007 ┆ 5        ┆ 2269.07667 ┆ 201.56455         ┆ 8.88              │
└─────────────┴────────────┴───────┴──────────┴────────────┴───────────────────┴───────────────────┘

### VI.f Calculate indicators by group, calculate the share of people per department with a Bac+5 or higher

In [40]:
# Calculate the percentage of people with a Bac+5 or higher degree per department and round the result to 2 decimal places
POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS_DEP = (
    POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS
    .with_columns(
        # Create a new "DEP" column containing the department code from the "GEO" column
        DEP=pl.when(
            pl.col("GEO").str.starts_with("97") # For overseas departments (e.g., 971, 972, 973, 974, 976)
            | pl.col("GEO").str.starts_with("98")
        )
        .then(
            pl.col("GEO").str.slice(0, 3) # 3 first characters for overseas territories (e.g., 971, 976, ...)
        )  
        .otherwise(
            pl.col("GEO").str.slice(0, 2) # 2 first characters for mainland France (e.g., 75, 69)
        )
    )
    .group_by("DEP") # Group by department
    .agg(POP_DEP=pl.col("POP_IRIS").sum(), # Sum population per department, creating POP_DEP column
         DIPLO_DEP=pl.col("POP_DIPLO_BAC_PLUS_5_OU_PLUS").sum()) # Sum bac + 5 or higher per department, creating DIPLO_DEP column

    .with_columns(
        (
            pl.col("DIPLO_DEP")
            / pl.col("POP_DEP")
            * 100 # Calculate the percentage of people with a Bac+5 or higher degree per department
        )
        .round(2) # Round the result to 2 decimal places
        .alias("POURCENTAGE_DIPLO_BAC_PLUS_5_OU_PLUS_DEP") # Name the new column "POURCENTAGE_DIPLO_BAC_PLUS_5_OU_PLUS_DEP"
    )
    .sort(by=["POURCENTAGE_DIPLO_BAC_PLUS_5_OU_PLUS_DEP"], descending=[True]))# Sort in descending order by the percentage of people with a Bac+5 or higher degree per department

# 5 first rows of the dataframe POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS_DEP
POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS_DEP.head(5)

shape: (5, 4)
┌─────┬──────────┬──────────────┬─────────────────────────────────┐
│ DEP ┆ POP_DEP  ┆ DIPLO_DEP    ┆ POURCENTAGE_DIPLO_BAC_PLUS_5_O… │
│ --- ┆ ---      ┆ ---          ┆ ---                             │
│ str ┆ f64      ┆ f64          ┆ f64                             │
╞═════╪══════════╪══════════════╪═════════════════════════════════╡
│ 75  ┆ 1.8355e6 ┆ 665338.77298 ┆ 36.25                           │
│ 92  ┆ 1.3570e6 ┆ 412768.82176 ┆ 30.42                           │
│ 78  ┆ 1.1922e6 ┆ 252709.33111 ┆ 21.2                            │
│ 94  ┆ 1.1606e6 ┆ 212551.34226 ┆ 18.31                           │
│ 69  ┆ 1.5709e6 ┆ 270718.42906 ┆ 17.23                           │
└─────┴──────────┴──────────────┴─────────────────────────────────┘

### VI.g Sort a table

In [41]:
# Sort POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS by descending percentage of people with a Bac+5 or higher degree
POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS = POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS.sort(by=["POURCENTAGE_DIPLO_BAC_PLUS_5_OU_PLUS"], descending=[True])

# 5 first rows of the dataframe POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS
POP_IRIS_DIPLO_BAC_PLUS_5_OU_PLUS.head(5)

shape: (5, 7)
┌─────────────┬────────────┬───────────┬──────────┬──────────┬──────────────────┬──────────────────┐
│ TIME_PERIOD ┆ GEO_OBJECT ┆ GEO       ┆ LAB_IRIS ┆ POP_IRIS ┆ POP_DIPLO_BAC_PL ┆ POURCENTAGE_DIPL │
│ ---         ┆ ---        ┆ ---       ┆ ---      ┆ ---      ┆ US_5_OU_PLUS     ┆ O_BAC_PLUS_5_O…  │
│ str         ┆ str        ┆ str       ┆ str      ┆ f64      ┆ ---              ┆ ---              │
│             ┆            ┆           ┆          ┆          ┆ f64              ┆ f64              │
╞═════════════╪════════════╪═══════════╪══════════╪══════════╪══════════════════╪══════════════════╡
│ 2023        ┆ COM        ┆ 31127     ┆ 5        ┆ 3.0      ┆ 3.0              ┆ 100.0            │
│ 2023        ┆ IRIS       ┆ 692660401 ┆ 3        ┆ 0.94608  ┆ 0.94608          ┆ 100.0            │
│ 2023        ┆ IRIS       ┆ 974080602 ┆ 3        ┆ 3.04455  ┆ 3.04455          ┆ 100.0            │
│ 2023        ┆ COM        ┆ 31146     ┆ 5        ┆ 9.0      ┆ 6.42857          ┆ 71.43            │
│ 2023        ┆ IRIS       ┆ 783720108 ┆ 3        ┆ 64.38939 ┆ 44.55073         ┆ 69.19            │
└─────────────┴────────────┴───────────┴──────────┴──────────┴──────────────────┴──────────────────┘